/* Generic import slot: one entity accepts models, images, audio, IES, HDRI, video or data. */
import { el } from '../kit.js';
import { stepper, pillToggle } from './controls.js';
import { bus } from '../bus.js';
const kinds=['Auto Detect','3D Model','Image / Texture','Audio','IES Light','HDRI','Video','Data'];
const modes=['Reference','Embed','Copy into project'];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fmtBytes=n=>!n?'—':n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;

export function assetPanel(node,ctx){
 const{compact=false,setProp,register}=ctx,P=node.props,host=el('div','mpanel assetpanel'),pos=()=>P.pos||[0,0,0],rot=()=>P.rot||[0,0,0],scale=()=>P.scale||[1,1,1];
 const canvas=(cv,h)=>{const w=cv.clientWidth||290,d=Math.min(devicePixelRatio||1,2);if(cv.width!==w*d||cv.height!==h*d){cv.width=w*d;cv.height=h*d}cv.style.height=h+'px';const g=cv.getContext('2d');g.setTransform(d,0,0,d,0,0);return[g,w,h]};

 const hero=el('div','pcard mp-hero as-hero'),cv=el('canvas'),drop=el('div','as-drop',`<span class="as-plus">+</span><b>DROP ASSET HERE</b><span>OBJ · GLTF · IMAGE · AUDIO · IES · HDRI · VIDEO</span>`),cap=el('div','mp-cap',`<div class="l"><b>Asset Slot</b><span class="mp-illum as-sub">READY FOR SOURCE</span></div><div class="r">UNBOUND</div>`);hero.append(cv,drop,cap);host.append(hero);
 const input=el('input');input.type='file';input.hidden=true;host.append(input);const importFile=f=>f&&bus.emit('assetfile',{node,file:f});input.onchange=()=>importFile(input.files?.[0]);
 ['dragenter','dragover'].forEach(ev=>hero.addEventListener(ev,e=>{e.preventDefault();hero.classList.add('file-over');e.dataTransfer.dropEffect='copy'}));hero.addEventListener('dragleave',e=>{if(!hero.contains(e.relatedTarget))hero.classList.remove('file-over')});hero.addEventListener('drop',e=>{e.preventDefault();hero.classList.remove('file-over');importFile(e.dataTransfer.files?.[0])});drop.onclick=()=>input.click();
 function paintHero(){const[g,w,h]=canvas(cv,compact?145:176),kind=P.assetKind||'Auto Detect';g.clearRect(0,0,w,h);g.fillStyle='#050505';g.fillRect(0,0,w,h);g.strokeStyle='rgba(255,255,255,.06)';for(let x=0;x<w;x+=24){g.beginPath();g.moveTo(x,0);g.lineTo(x,h);g.stroke()}for(let y=0;y<h;y+=24){g.beginPath();g.moveTo(0,y);g.lineTo(w,y);g.stroke()}
  if(P.sourceName){const cx=w/2,cy=h*.43;if(kind==='Image / Texture'||kind==='HDRI'||kind==='Video'){const gr=g.createLinearGradient(30,20,w-30,h-34);gr.addColorStop(0,'#224b68');gr.addColorStop(.45,'#b66b60');gr.addColorStop(1,'#1b1628');g.fillStyle=gr;g.fillRect(30,16,w-60,h-48);g.strokeStyle='rgba(255,255,255,.6)';g.strokeRect(30.5,16.5,w-61,h-49)}else if(kind==='Audio'){g.strokeStyle='#b78dff';g.beginPath();for(let x=12;x<w-12;x++){const t=x/w*25,y=cy+(Math.sin(t)+.4*Math.sin(t*3.7)+.2*Math.sin(t*8.2))*30*(1-x/w);x===12?g.moveTo(x,y):g.lineTo(x,y)}g.stroke()}else if(kind==='IES Light'){for(let a=-Math.PI;a<Math.PI;a+=.035){const r=18+45*Math.pow(Math.max(0,Math.cos(a*.72)),6),x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;g.strokeStyle='rgba(246,220,114,.4)';g.beginPath();g.moveTo(cx,cy);g.lineTo(x,y);g.stroke()}}else{g.save();g.translate(cx,cy);g.strokeStyle='#d4a5ff';g.fillStyle='rgba(212,165,255,.12)';g.beginPath();g.moveTo(-42,-26);g.lineTo(10,-42);g.lineTo(43,-20);g.lineTo(38,29);g.lineTo(-12,43);g.lineTo(-43,20);g.closePath();g.fill();g.stroke();g.beginPath();g.moveTo(-42,-26);g.lineTo(-10,-4);g.lineTo(43,-20);g.moveTo(-10,-4);g.lineTo(-12,43);g.stroke();g.restore()}
   g.fillStyle='rgba(255,255,255,.38)';g.font='8px ui-sans-serif';g.textAlign='center';g.fillText(P.sourceName,w/2,h-12)}
  drop.classList.toggle('bound',!!P.sourceName);cap.querySelector('b').textContent=P.sourceName||'Asset Slot';cap.querySelector('.as-sub').textContent=P.sourceName?`${kind} · ${P.mime||'unknown media type'}`:'Create the entity, then drop any supported file';cap.querySelector('.r').textContent=P.sourceName?fmtBytes(P.sourceBytes):'UNBOUND';
 }

 const rail=el('div','mp-rail');const metric=k=>{const e=el('div','mp-pill',`<b class="v">—</b><span class="k">${k}</span>`);rail.append(e);return e.querySelector('.v')};const mState=metric('State'),mType=metric('Type'),mSize=metric('Size'),mMode=metric('Mode');host.append(rail);

 const source=el('div','pcard mp-metric as-source');source.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Source</span><span class="s">External asset binding</span></div></div><div class="mp-num"><span class="i">—</span><span class="d"></span><span class="u"></span></div><div class="mp-k mp-target">File <span class="v">—</span></div>`;const actions=el('div','as-actions'),choose=el('button','as-btn','CHOOSE FILE'),replace=el('button','as-btn ghost','REPLACE');choose.onclick=replace.onclick=()=>input.click();actions.append(choose,replace);source.append(actions);host.append(source);

 const type=el('div','pcard mp-light as-types');type.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Asset type</span><span class="s">Auto-detected from extension · override here</span></div></div>`;const tb=el('div','pbody'),kindTags=el('div','mp-tags as-kindtags');kinds.forEach(k=>{const b=el('button',`mp-tag${P.assetKind===k?' on':''}`,k.toUpperCase());b.onclick=()=>{setProp(node,'assetKind',k);paintAll()};kindTags.append(b)});tb.append(kindTags);const matrix=el('div','as-matrix');matrix.innerHTML=`<div><b>3D</b><span>.gltf .glb .obj .fbx .usd .stl</span></div><div><b>IMAGE</b><span>.png .jpg .webp .tga .exr .hdr</span></div><div><b>AUDIO</b><span>.wav .mp3 .ogg .flac .m4a</span></div><div><b>LIGHT</b><span>.ies photometric profiles</span></div><div><b>MEDIA</b><span>.mp4 .webm .mov .json .csv .bin</span></div>`;tb.append(matrix);type.append(tb);host.append(type);type.querySelector('.mp-chead .l').onclick=()=>type.classList.toggle('shut');

 const options=el('div','pcard mp-light as-options');options.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Import policy</span><span class="s">Source ownership · live reload</span></div></div>`;const ob=el('div','pbody'),modeTags=el('div','mp-tags');modes.forEach(k=>{const b=el('button',`mp-tag${P.importMode===k?' on':''}`,k.toUpperCase());b.onclick=()=>{setProp(node,'importMode',k);paintAll()};modeTags.append(b)});ob.append(modeTags);const stateTags=el('div','mp-tags'),watch=pillToggle('WATCH SOURCE',P.autoReload!==false,v=>{setProp(node,'autoReload',v);paintAll()}),preview=pillToggle('GENERATE PREVIEW',P.generatePreview!==false,v=>{setProp(node,'generatePreview',v);paintAll()});stateTags.append(watch,preview);ob.append(stateTags);const note=el('div','mp-note');ob.append(note);options.append(ob);host.append(options);

 const transform=el('div','pcard mp-light as-transform');transform.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Transform</span><span class="s">Placement after import</span></div></div>`;const xb=el('div','pbody'),syncs=[];transform.append(xb);
 const addVec=(label,key,get,unit)=>{const h=el('div','mp-subhead',`<span class="k">${label}</span>`),row=el('div','as-steppers');['X','Y','Z'].forEach((k,i)=>{const x=el('div','as-axis',`<span>${k}</span>`),s=stepper({value:get()[i],min:key==='scale'?.01:-999,max:999,dec:2,step:key==='rot'?1:.05,unit:i===0?unit:'',onInput:v=>{const a=[...get()];a[i]=v;setProp(node,key,a);paintAll()}});x.append(s);x._step=s;row.append(x)});xb.append(h,row);syncs.push(()=>[...row.children].forEach((x,i)=>x._step._set(get()[i])))};addVec('position','pos',pos,'m');addVec('rotation','rot',rot,'°');addVec('scale','scale',scale,'×');host.append(transform);transform.querySelector('.mp-chead .l').onclick=()=>transform.classList.toggle('shut');

 function paintAll(){paintHero();mState.textContent=P.status||'EMPTY';mType.textContent=(P.assetKind||'Auto').replace(' / Texture','');mSize.textContent=fmtBytes(P.sourceBytes);mMode.textContent=P.importMode?.split(' ')[0]||'REF';const bytes=P.sourceBytes||0,whole=!bytes?'0':bytes<1024?String(bytes):bytes>=1048576?(bytes/1048576).toFixed(1):(bytes/1024).toFixed(1);source.querySelector('.mp-num .i').textContent=whole;source.querySelector('.mp-num .u').textContent=bytes<1024?'B':bytes>=1048576?'MB':'KB';source.querySelector('.mp-target .v').textContent=P.sourceName||'No source bound';replace.style.display=P.sourceName?'':'none';[...kindTags.children].forEach((b,i)=>b.classList.toggle('on',kinds[i]===P.assetKind));[...modeTags.children].forEach((b,i)=>b.classList.toggle('on',modes[i]===P.importMode));watch._set(P.autoReload!==false);preview._set(P.generatePreview!==false);note.textContent=P.sourceName?`${P.importMode}. ${P.autoReload?'The source will be watched for changes.':'Source watching is disabled.'}`:'Drop a file on this panel or directly onto the Asset Slot row in the Outliner.';syncs.forEach(f=>f())}
 register?.(paintAll);const ro=new ResizeObserver(paintHero);ro.observe(host);host._dispose=()=>ro.disconnect();requestAnimationFrame(paintAll);paintAll();return host;
}
