/* Camera instruments: perspective, cinematic, player-follow and vehicle/chase rigs. */
import { el } from '../kit.js';
import { tape, stepper, pillToggle } from './controls.js';
import { typeOf } from '../world.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const gates={'16:9':16/9,'2.39:1':2.39,'4:3':4/3,'1:1':1};
const dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2]);
const fovFromFocal=(f,s=36)=>2*Math.atan(s/(2*f))*180/Math.PI;
const focalFromFov=(f,s=36)=>s/(2*Math.tan(f*Math.PI/360));
const hyperfocal=(f,N,c=.03)=>f*f/(N*c)+f;

export function cameraPanel(node,ctx){
 const{compact=false,setProp,register}=ctx,P=node.props,kind=node.type,cine=kind==='cinecamera',player=kind==='playercamera',vehicle=kind==='vehiclecamera',host=el('div','mpanel camerapanel');
 const pos=()=>P.pos||[0,0,0],look=()=>P.lookAt||[0,0,0],focus=()=>P.focus??dist(pos(),look()),fov=()=>P.fov??46;
 const canvas=(cv,h)=>{const w=cv.clientWidth||290,d=Math.min(devicePixelRatio||1,2);if(cv.width!==w*d||cv.height!==h*d){cv.width=w*d;cv.height=h*d}cv.style.height=h+'px';const g=cv.getContext('2d');g.setTransform(d,0,0,d,0,0);return[g,w,h]};

 /* viewfinder */
 const hero=el('div','pcard mp-hero ca-hero'),cv=el('canvas');cv.title=cine?'Drag across for focal length; vertically for focus':'Drag across for field of view';const cap=el('div','mp-cap',`<div class="l"><b>${typeOf(node).label}</b><span class="mp-illum ca-sub">LIVE VIEWFINDER</span></div><div class="r">—</div>`);hero.append(cv,cap);host.append(hero);let mark=null;
 function paintHero(){const[g,w,h]=canvas(cv,compact?148:178),ratio=gates[P.gate]||16/9;g.clearRect(0,0,w,h);const sky=g.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#19242e');sky.addColorStop(.55,'#0d1116');sky.addColorStop(1,'#050506');g.fillStyle=sky;g.fillRect(0,0,w,h);
  const frameW=w-18,frameH=Math.min(h-16,frameW/ratio),x=(w-frameW)/2,y=(h-frameH)/2;g.save();g.beginPath();g.rect(x,y,frameW,frameH);g.clip();
  /* abstract studio targets, changing apparent size with FOV */
  const zoom=46/fov();g.strokeStyle='rgba(255,255,255,.12)';for(let i=-5;i<=5;i++){g.beginPath();g.moveTo(w/2+i*28*zoom,h*.58);g.lineTo(w/2+i*62*zoom,h);g.stroke()}for(let i=0;i<6;i++){const yy=h*.58+(h*.42)*i*i/25;g.beginPath();g.moveTo(0,yy);g.lineTo(w,yy);g.stroke()}
  const objects=[[-.28,.53,32], [.04,.46,22], [.27,.58,27]];objects.forEach(([xx,yy,r],i)=>{const cx=w/2+xx*w*zoom,cy=h*yy,rr=r*zoom;g.fillStyle=['#c24f48','#8baed0','#a78bfa'][i];if(i===1){g.beginPath();g.arc(cx,cy,rr*.65,0,Math.PI*2);g.fill()}else g.fillRect(cx-rr*.55,cy-rr,rr*1.1,rr*2)});
  /* composition grid + safe frame */
  g.strokeStyle='rgba(255,255,255,.18)';g.setLineDash([2,3]);[1/3,2/3].forEach(t=>{g.beginPath();g.moveTo(x+frameW*t,y);g.lineTo(x+frameW*t,y+frameH);g.moveTo(x,y+frameH*t);g.lineTo(x+frameW,y+frameH*t);g.stroke()});g.setLineDash([]);g.strokeStyle='rgba(255,255,255,.30)';g.strokeRect(x+frameW*.05,y+frameH*.05,frameW*.9,frameH*.9);
  g.restore();g.fillStyle='rgba(0,0,0,.88)';g.fillRect(0,0,w,y);g.fillRect(0,y+frameH,w,h-y-frameH);g.fillRect(0,y,x,frameH);g.fillRect(x+frameW,y,w-x-frameW,frameH);g.strokeStyle='rgba(255,255,255,.55)';g.strokeRect(x+.5,y+.5,frameW-1,frameH-1);
  g.font='8px ui-sans-serif';g.fillStyle='rgba(255,255,255,.55)';g.textAlign='left';g.fillText(`${P.gate}  ${fov().toFixed(1)}°`,x+6,y+12);g.textAlign='right';g.fillText(cine?`${P.focal.toFixed(0)} mm  f/${P.aperture.toFixed(1)}  ISO ${P.iso}`:`NEAR ${(P.near??.1).toFixed(2)} m`,x+frameW-6,y+12);
  const cx=w/2,cy=y+frameH/2;g.strokeStyle='rgba(255,255,255,.55)';g.beginPath();g.moveTo(cx-8,cy);g.lineTo(cx+8,cy);g.moveTo(cx,cy-8);g.lineTo(cx,cy+8);g.stroke();if(mark){g.strokeStyle='rgba(255,255,255,.4)';g.setLineDash([2,3]);g.beginPath();g.moveTo(mark.x,0);g.lineTo(mark.x,h);g.moveTo(0,mark.y);g.lineTo(w,mark.y);g.stroke();g.setLineDash([])}
  cap.querySelector('.ca-sub').textContent=cine?`${P.focal.toFixed(0)} mm · ${P.sensorWidth.toFixed(1)} mm sensor · ${focus().toFixed(1)} m focus`:vehicle?`${P.mode} mount · ${P.distance.toFixed(1)} m chase`:player?`${P.boom.toFixed(1)} m boom · ${P.damping.toFixed(2)} damping`:`${fov().toFixed(1)}° field · ${focus().toFixed(1)} m focus`;cap.querySelector('.r').textContent=P.gate;
 }
 const heroFrom=e=>{const r=cv.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width,0,1),y=clamp((e.clientY-r.top)/r.height,0,1);mark={x:x*r.width,y:y*r.height};if(cine){const focal=12+x*188;setProp(node,'focal',+focal.toFixed(1));setProp(node,'fov',+fovFromFocal(focal,P.sensorWidth).toFixed(1));setProp(node,'focus',+(.2+(1-y)*49.8).toFixed(1))}else{const lo=player?35:vehicle?35:12,hi=player?120:vehicle?130:120;setProp(node,'fov',+(lo+x*(hi-lo)).toFixed(1));if(player)setProp(node,'damping',+(1-y).toFixed(2));if(vehicle)setProp(node,'lag',+(1-y).toFixed(2))}paintAll()};cv.onpointerdown=e=>{cv.setPointerCapture(e.pointerId);cv.classList.add('grabbing');heroFrom(e)};cv.onpointermove=e=>{if(cv.hasPointerCapture?.(e.pointerId))heroFrom(e)};cv.onpointerup=()=>{mark=null;cv.classList.remove('grabbing');paintHero()};

 const rail=el('div','mp-rail');const metric=k=>{const e=el('div','mp-pill',`<b class="v">—</b><span class="k">${k}</span>`);rail.append(e);return e.querySelector('.v')};const mLens=metric(cine?'Focal':'Field'),mFocus=metric(cine?'Focus':'Target'),mGate=metric('Gate'),mRig=metric(cine?'T-stop':player?'Boom':vehicle?'Lag':'Clip');host.append(rail);

 /* framing and lens projection */
 const fc=el('div','pcard mp-metric ca-frame');fc.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Framing</span><span class="s">Gate geometry · projection</span></div></div><div class="mp-num"><span class="i">—</span><span class="d"></span><span class="u">°</span></div><div class="mp-k mp-target">Horizontal field <span class="v">—</span></div>`;const fw=el('div','mp-chartwrap'),frustum=el('canvas');fw.append(frustum);fc.append(fw);const gateTags=el('div','mp-tags ca-gates');Object.keys(gates).forEach(v=>{const b=el('button',`mp-tag${P.gate===v?' on':''}`,v);b.onclick=()=>{setProp(node,'gate',v);paintAll()};gateTags.append(b)});fc.append(gateTags);host.append(fc);
 function paintFrustum(){const[g,w,h]=canvas(frustum,108),cx=w/2,base=h-17,ang=fov()*Math.PI/360,len=Math.min(w*.42,(base-8)/Math.max(.15,Math.cos(ang))),dx=Math.sin(ang)*len,dy=Math.cos(ang)*len;g.clearRect(0,0,w,h);g.fillStyle='#050505';g.fillRect(0,0,w,h);const gr=g.createLinearGradient(0,base,0,8);gr.addColorStop(0,'rgba(105,195,255,.25)');gr.addColorStop(1,'rgba(105,195,255,.03)');g.fillStyle=gr;g.beginPath();g.moveTo(cx,base);g.lineTo(cx-dx,base-dy);g.lineTo(cx+dx,base-dy);g.closePath();g.fill();g.strokeStyle='rgba(255,255,255,.7)';g.beginPath();g.moveTo(cx-dx,base-dy);g.lineTo(cx,base);g.lineTo(cx+dx,base-dy);g.stroke();[.25,.5,.75].forEach(t=>{g.strokeStyle='rgba(255,255,255,.1)';g.beginPath();g.moveTo(cx-dx*t,base-dy*t);g.lineTo(cx+dx*t,base-dy*t);g.stroke()});g.fillStyle='rgba(255,255,255,.3)';g.font='8px ui-sans-serif';g.textAlign='center';g.fillText(`${fov().toFixed(1)}° FIELD`,cx,h-3)}

 /* type-specific instrument */
 let typeTapes=[],typeSync=()=>{};
 if(cine){
  const[c,b]=panelCard('Cinema lens','Depth of field · exposure triangle'),dof=el('div','mp-meter ca-dof','<div class="hd"><span class="k">depth of field · metres</span></div>'),dcv=el('canvas');dof.append(dcv);b.append(dof);
  const focal=tape({label:'Focal length',min:12,max:200,value:P.focal,dec:0,step:1,unit:'mm',marks:[{t:0,l:'12 WIDE'},{t:.202,l:'50 mm'},{t:1,l:'200 TELE'}],onInput:v=>{setProp(node,'focal',Math.round(v));setProp(node,'fov',+fovFromFocal(v,P.sensorWidth).toFixed(1));paintAll()}}),focusT=tape({label:'Focus distance',min:.2,max:100,value:P.focus,dec:1,step:.1,unit:'m',toPos:v=>Math.log(v/.2)/Math.log(500),fromPos:t=>.2*Math.pow(500,t),marks:[{t:0,l:'.2 m'},{t:.63,l:'10 m'},{t:1,l:'100 m'}],onInput:v=>{setProp(node,'focus',v);paintAll()}}),ap=tape({label:'Aperture',min:.7,max:22,value:P.aperture,dec:1,step:.1,unit:'f',marks:[{t:0,l:'f/.7'},{t:.1,l:'2.8'},{t:1,l:'f/22'}],onInput:v=>{setProp(node,'aperture',v);paintAll()}});b.append(focal,focusT,ap);host.append(c);
  function paintDof(){const[g,w,h]=canvas(dcv,92),f=P.focal,N=P.aperture,s=P.focus*1000,H=hyperfocal(f,N),near=H*s/(H+s-f)/1000,far=s>=H?Infinity:H*s/(H-s+f)/1000,px=m=>8+Math.log10(Math.max(.2,m)/.2)/Math.log10(500)*(w-16);g.clearRect(0,0,w,h);g.fillStyle='#050505';g.fillRect(0,0,w,h);g.fillStyle='rgba(105,195,255,.22)';g.fillRect(px(near),30,(isFinite(far)?px(Math.min(100,far)):w-8)-px(near),25);g.strokeStyle='#fff';g.beginPath();g.moveTo(px(P.focus),20);g.lineTo(px(P.focus),66);g.stroke();g.fillStyle='rgba(255,255,255,.3)';g.font='8px ui-sans-serif';g.textAlign='left';g.fillText('.2 m',8,h-7);g.textAlign='center';g.fillText('10 m',px(10),h-7);g.textAlign='right';g.fillText('∞',w-8,h-7);g.textAlign='center';g.fillText(`${near.toFixed(1)} — ${isFinite(far)?far.toFixed(1):'∞'} m`,w/2,18)}
  const[ec,eb]=panelCard('Exposure','Motion cadence · sensor gain');const shutter=tape({label:'Shutter angle',min:1,max:360,value:P.shutterAngle,dec:0,step:1,unit:'°',marks:[{t:0,l:'1°'},{t:.5,l:'180°'},{t:1,l:'360°'}],onInput:v=>{setProp(node,'shutterAngle',Math.round(v));paintAll()}}),iso=tape({label:'Sensor ISO',min:25,max:12800,value:P.iso,dec:0,step:25,toPos:v=>Math.log2(v/25)/Math.log2(512),fromPos:t=>25*Math.pow(512,t),marks:[{t:0,l:'25'},{t:.556,l:'800'},{t:1,l:'12 800'}],onInput:v=>{setProp(node,'iso',Math.round(v/25)*25);paintAll()}}),sensor=tape({label:'Sensor width',min:12,max:70,value:P.sensorWidth,dec:1,step:.5,unit:'mm',marks:[{t:0,l:'S16 12'},{t:.414,l:'FF 36'},{t:1,l:'70 mm'}],onInput:v=>{setProp(node,'sensorWidth',v);setProp(node,'fov',+fovFromFocal(P.focal,v).toFixed(1));paintAll()}}),squeeze=tape({label:'Anamorphic squeeze',min:1,max:2,value:P.squeeze,dec:2,step:.05,unit:'×',marks:[{t:0,l:'SPHERICAL'},{t:.33,l:'1.33×'},{t:1,l:'2×'}],onInput:v=>{setProp(node,'squeeze',v);paintAll()}});eb.append(shutter,iso,sensor,squeeze);host.append(ec);typeTapes=[focal,focusT,ap,shutter,iso,sensor,squeeze];typeSync=()=>{paintDof();[focal,focusT,ap,shutter,iso,sensor,squeeze].forEach((t,i)=>t._set([P.focal,P.focus,P.aperture,P.shutterAngle,P.iso,P.sensorWidth,P.squeeze][i]))};
 } else if(player){
  const[c,b]=panelCard('Player rig','Spring arm · collision · response'),rig=el('div','mp-meter ca-rig','<div class="hd"><span class="k">third-person spring arm</span></div>'),rcv=el('canvas');rig.append(rcv);b.append(rig);
  const boom=tape({label:'Boom length',min:0,max:12,value:P.boom,dec:1,step:.1,unit:'m',marks:[{t:0,l:'FIRST PERSON'},{t:.35,l:'4.2 m'},{t:1,l:'12 m'}],onInput:v=>{setProp(node,'boom',v);paintAll()}}),shoulder=tape({label:'Shoulder offset',min:-2,max:2,value:P.shoulder,dec:2,step:.05,unit:'m',marks:[{t:0,l:'LEFT'},{t:.5,l:'CENTRE'},{t:1,l:'RIGHT'}],onInput:v=>{setProp(node,'shoulder',v);paintAll()}}),damping=tape({label:'Follow damping',min:0,max:1,value:P.damping,dec:2,step:.01,marks:[{t:0,l:'RIGID'},{t:.72,l:'FOLLOW .72'},{t:1,l:'FLOAT'}],onInput:v=>{setProp(node,'damping',v);paintAll()}}),fovT=tape({label:'Field of view',min:35,max:120,value:P.fov,dec:0,step:1,unit:'°',marks:[{t:0,l:'35°'},{t:.435,l:'PLAYER 72°'},{t:1,l:'120°'}],onInput:v=>{setProp(node,'fov',v);paintAll()}});b.append(boom,shoulder,damping,fovT);const tags=el('div','mp-tags'),collision=pillToggle('CAMERA COLLISION',P.collision!==false,v=>{setProp(node,'collision',v);paintAll()}),input=pillToggle('PLAYER INPUT',P.input!==false,v=>{setProp(node,'input',v);paintAll()});tags.append(collision,input);b.append(tags);host.append(c);
  function paintRig(){const[g,w,h]=canvas(rcv,104),ground=h-16,px=w*.68,py=ground-33,cx=px-P.boom/12*w*.52,cy=py-14;g.clearRect(0,0,w,h);g.fillStyle='#050505';g.fillRect(0,0,w,h);g.strokeStyle='rgba(255,255,255,.15)';g.beginPath();g.moveTo(8,ground);g.lineTo(w-8,ground);g.stroke();g.fillStyle='rgba(255,255,255,.55)';g.fillRect(px-7,py-22,14,22);g.beginPath();g.arc(px,py-29,7,0,Math.PI*2);g.fill();g.strokeStyle='#69c3ff';g.lineWidth=2;g.beginPath();g.moveTo(px,py-20);g.lineTo(cx,cy);g.stroke();g.lineWidth=1;g.fillStyle='#69c3ff';g.fillRect(cx-7,cy-5,14,10);g.setLineDash([3,3]);g.strokeStyle='rgba(105,195,255,.45)';g.beginPath();g.moveTo(cx,cy);g.lineTo(px,py-12);g.stroke();g.setLineDash([])}
  typeTapes=[boom,shoulder,damping,fovT];typeSync=()=>{paintRig();[boom,shoulder,damping,fovT].forEach((t,i)=>t._set([P.boom,P.shoulder,P.damping,P.fov][i]));collision._set(P.collision);input._set(P.input)};
 } else if(vehicle){
  const[c,b]=panelCard('Vehicle rig','Mount preset · velocity response'),rig=el('div','mp-meter ca-car','<div class="hd"><span class="k">automotive camera envelope</span></div>'),rcv=el('canvas');rig.append(rcv);b.append(rig);const modes=el('div','mp-tags ca-modes');['Chase','Bumper','Cockpit','Hood','Orbit Rig'].forEach(v=>{const x=el('button',`mp-tag${P.mode===v?' on':''}`,v.toUpperCase());x.onclick=()=>{setProp(node,'mode',v);paintAll()};modes.append(x)});b.append(modes);
  const distanceT=tape({label:'Follow distance',min:0,max:20,value:P.distance,dec:1,step:.1,unit:'m',marks:[{t:0,l:'MOUNTED'},{t:.325,l:'CHASE 6.5'},{t:1,l:'20 m'}],onInput:v=>{setProp(node,'distance',v);paintAll()}}),height=tape({label:'Mount height',min:.2,max:6,value:P.height,dec:1,step:.1,unit:'m',marks:[{t:0,l:'BUMPER'},{t:.276,l:'1.8 m'},{t:1,l:'6 m'}],onInput:v=>{setProp(node,'height',v);paintAll()}}),lag=tape({label:'Velocity lag',min:0,max:1,value:P.lag,dec:2,step:.01,marks:[{t:0,l:'LOCKED'},{t:.35,l:'CHASE .35'},{t:1,l:'DRIFT'}],onInput:v=>{setProp(node,'lag',v);paintAll()}}),ahead=tape({label:'Look ahead',min:0,max:50,value:P.lookAhead,dec:0,step:1,unit:'m',marks:[{t:0,l:'CAR'},{t:.24,l:'12 m'},{t:1,l:'50 m'}],onInput:v=>{setProp(node,'lookAhead',Math.round(v));paintAll()}}),shake=tape({label:'Road vibration',min:0,max:1,value:P.shake,dec:2,step:.01,marks:[{t:0,l:'STABILIZED'},{t:.12,l:'.12'},{t:1,l:'RAW'}],onInput:v=>{setProp(node,'shake',v);paintAll()}});b.append(distanceT,height,lag,ahead,shake);const tags=el('div','mp-tags'),horizon=pillToggle('HORIZON LOCK',P.horizonLock!==false,v=>{setProp(node,'horizonLock',v);paintAll()}),collision=pillToggle('COLLISION SWEEP',P.collision!==false,v=>{setProp(node,'collision',v);paintAll()});tags.append(horizon,collision);b.append(tags);host.append(c);
  function paintCar(){const[g,w,h]=canvas(rcv,110),base=h-22,carX=w*.63;g.clearRect(0,0,w,h);g.fillStyle='#050505';g.fillRect(0,0,w,h);g.strokeStyle='rgba(255,255,255,.1)';for(let x=0;x<w;x+=24){g.beginPath();g.moveTo(x,8);g.lineTo(x,h-8);g.stroke()}g.fillStyle='#343a42';g.beginPath();g.roundRect(carX-42,base-24,84,22,8);g.fill();g.fillStyle='#111';[carX-27,carX+27].forEach(x=>{g.beginPath();g.arc(x,base,9,0,Math.PI*2);g.fill()});const cx=carX-P.distance/20*w*.5,cy=base-20-P.height/6*h*.55;g.strokeStyle='#5eead4';g.beginPath();g.moveTo(carX,base-20);g.lineTo(cx,cy);g.stroke();g.fillStyle='#5eead4';g.fillRect(cx-8,cy-5,16,10);g.setLineDash([3,3]);g.strokeStyle='rgba(94,234,212,.4)';g.beginPath();g.moveTo(cx,cy);g.lineTo(carX+P.lookAhead/50*w*.28,base-15);g.stroke();g.setLineDash([])}
  typeTapes=[distanceT,height,lag,ahead,shake];typeSync=()=>{paintCar();[distanceT,height,lag,ahead,shake].forEach((t,i)=>t._set([P.distance,P.height,P.lag,P.lookAhead,P.shake][i]));horizon._set(P.horizonLock);collision._set(P.collision);[...modes.children].forEach((b,i)=>b.classList.toggle('on',['Chase','Bumper','Cockpit','Hood','Orbit Rig'][i]===P.mode))};
 } else {
  const[c,b]=panelCard('Perspective lens','Field · focus · aperture'),fovT=tape({label:'Field of view',min:12,max:120,value:P.fov,dec:0,step:1,unit:'°',marks:[{t:0,l:'TELE 12°'},{t:.315,l:'46°'},{t:1,l:'ULTRA 120°'}],onInput:v=>{setProp(node,'fov',v);paintAll()}}),focusT=tape({label:'Focus distance',min:.2,max:80,value:P.focus,dec:1,step:.1,unit:'m',marks:[{t:0,l:'.2 m'},{t:.148,l:'12 m'},{t:1,l:'80 m'}],onInput:v=>{setProp(node,'focus',v);paintAll()}}),ap=tape({label:'Aperture',min:.7,max:22,value:P.aperture,dec:1,step:.1,unit:'f',marks:[{t:0,l:'f/.7'},{t:.1,l:'2.8'},{t:1,l:'f/22'}],onInput:v=>{setProp(node,'aperture',v);paintAll()}}),shutter=tape({label:'Shutter',min:1,max:500,value:P.shutter,dec:0,step:1,unit:'1/s',marks:[{t:0,l:'1 s'},{t:.118,l:'1/60'},{t:1,l:'1/500'}],onInput:v=>{setProp(node,'shutter',Math.round(v));paintAll()}});b.append(fovT,focusT,ap,shutter);host.append(c);typeTapes=[fovT,focusT,ap,shutter];typeSync=()=>[fovT,focusT,ap,shutter].forEach((t,i)=>t._set([P.fov,P.focus,P.aperture,P.shutter][i]));
 }

 /* placement */
 const[pc,pb]=panelCard('Camera transform','World placement · look target'),plan=el('div','mp-meter ca-plan','<div class="hd"><span class="k">plan view · source to target</span></div>'),pcv=el('canvas');plan.append(pcv);pb.append(plan);const vecs=[];
 function addVec(label,key,get){const h=el('div','mp-subhead',`<span class="k">${label}</span>`),row=el('div','ca-steppers');['X','Y','Z'].forEach((k,i)=>{const x=el('div','ca-axis',`<span>${k}</span>`),s=stepper({value:get()[i],min:-999,max:999,dec:2,step:.05,unit:i===0?'m':'',onInput:v=>{const a=[...get()];a[i]=v;setProp(node,key,a);paintAll()}});x.append(s);x._step=s;row.append(x)});pb.append(h,row);vecs.push([row,get])}addVec('camera position','pos',pos);addVec('look target','lookAt',look);const tags=el('div','mp-tags'),frustumPill=pillToggle('DRAW FRUSTUM',P.showFrustum!==false,v=>{setProp(node,'showFrustum',v);paintAll()});tags.append(frustumPill);pb.append(tags);host.append(pc);
 function paintPlan(){const[g,w,h]=canvas(pcv,115),cx=w/2,cy=h/2,span=Math.min(w,h)-18,to=a=>[cx+clamp(a[0]/20,-1,1)*span/2,cy+clamp(a[2]/20,-1,1)*span/2],a=to(pos()),b=to(look());g.clearRect(0,0,w,h);g.fillStyle='#050505';g.fillRect(0,0,w,h);for(let i=-4;i<=4;i++){g.strokeStyle=i?'rgba(255,255,255,.06)':'rgba(255,255,255,.18)';g.beginPath();g.moveTo(cx+i*span/8,9);g.lineTo(cx+i*span/8,h-9);g.moveTo(cx-span/2,cy+i*span/8);g.lineTo(cx+span/2,cy+i*span/8);g.stroke()}g.strokeStyle='#69c3ff';g.beginPath();g.moveTo(...a);g.lineTo(...b);g.stroke();g.fillStyle='#fff';g.beginPath();g.arc(...b,4,0,Math.PI*2);g.fill();g.fillStyle='#69c3ff';g.fillRect(a[0]-6,a[1]-4,12,8)}
 const planFrom=e=>{const r=pcv.getBoundingClientRect(),span=Math.min(r.width,r.height)-18,x=clamp((e.clientX-r.left-r.width/2)/(span/2),-1,1)*20,z=clamp((e.clientY-r.top-r.height/2)/(span/2),-1,1)*20,a=[...pos()];a[0]=+x.toFixed(2);a[2]=+z.toFixed(2);setProp(node,'pos',a);paintAll()};pcv.onpointerdown=e=>{pcv.setPointerCapture(e.pointerId);pcv.classList.add('drag');planFrom(e)};pcv.onpointermove=e=>{if(pcv.hasPointerCapture?.(e.pointerId))planFrom(e)};pcv.onpointerup=e=>pcv.releasePointerCapture?.(e.pointerId);

 function panelCard(title,sub){const c=el('div','pcard mp-light');c.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">${title}</span><span class="s">${sub}</span></div></div>`;const b=el('div','pbody');c.append(b);c.querySelector('.mp-chead .l').onclick=()=>c.classList.toggle('shut');return[c,b]}
 function paintAll(){paintHero();paintFrustum();paintPlan();typeSync();const targetD=dist(pos(),look());mLens.innerHTML=cine?`${P.focal.toFixed(0)}<em>mm</em>`:`${fov().toFixed(0)}<em>°</em>`;mFocus.innerHTML=`${(cine?focus():targetD).toFixed(1)}<em>m</em>`;mGate.textContent=P.gate;mRig.innerHTML=cine?`f/${P.aperture.toFixed(1)}`:player?`${P.boom.toFixed(1)}<em>m</em>`:vehicle?`${P.lag.toFixed(2)}`:`${P.focus.toFixed(1)}<em>m</em>`;fc.querySelector('.mp-num .i').textContent=Math.floor(fov());fc.querySelector('.mp-num .d').textContent='.'+Math.round(fov()*10)%10;fc.querySelector('.mp-target .v').textContent=`${P.gate} · ${focalFromFov(fov(),P.sensorWidth||36).toFixed(0)} mm equivalent`;[...gateTags.children].forEach((b,i)=>b.classList.toggle('on',Object.keys(gates)[i]===P.gate));vecs.forEach(([r,get])=>[...r.children].forEach((x,i)=>x._step._set(get()[i])));frustumPill._set(P.showFrustum!==false)}
 register?.(paintAll);const ro=new ResizeObserver(()=>{paintHero();paintFrustum();paintPlan();typeTapes.forEach(t=>t._paint?.())});ro.observe(host);host._dispose=()=>ro.disconnect();requestAnimationFrame(paintAll);paintAll();return host;
}
