/* Curve authoring instrument: Bezier, Catmull-Rom, NURBS, polyline, arc and helix. */
import { el, colorChip } from '../kit.js';
import { tape, stepper, pillToggle } from './controls.js';
const kinds=['Bezier','Catmull-Rom','NURBS','Polyline','Arc','Helix'];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const defaultPoints=n=>Array.from({length:Math.max(2,n)},(_,i)=>{const t=i/Math.max(1,n-1);return[(t-.5)*8,Math.sin(t*Math.PI*2)*1.4,Math.cos(t*Math.PI*3)*1.2]});
const bez=(a,b,c,d,t)=>{const q=1-t;return a*q*q*q+3*b*q*q*t+3*c*q*t*t+d*t*t*t};
export function curvePanel(node,ctx){
 const{compact=false,setProp,register}=ctx,P=node.props,host=el('div','mpanel curvepanel'),pos=()=>P.pos||[0,0,0],rot=()=>P.rot||[0,0,0],scale=()=>P.scale||[1,1,1];if(!P.controlPoints)P.controlPoints=defaultPoints(P.pointCount||4);
 const canvas=(cv,h)=>{const w=cv.clientWidth||290,d=Math.min(devicePixelRatio||1,2);if(cv.width!==w*d||cv.height!==h*d){cv.width=w*d;cv.height=h*d}cv.style.height=h+'px';const g=cv.getContext('2d');g.setTransform(d,0,0,d,0,0);return[g,w,h]};
 const sample=()=>{const cp=P.controlPoints||defaultPoints(P.pointCount),out=[],kind=P.curveKind;if(kind==='Polyline')return cp.map(p=>[p[0],p[1]]);if(kind==='Arc')for(let i=0;i<=80;i++){const a=i/80*Math.PI*(P.closed?2:1.55);out.push([Math.cos(a)*3.5,Math.sin(a)*2.3])}else if(kind==='Helix')for(let i=0;i<=100;i++){const a=i/100*Math.PI*4;out.push([Math.cos(a)*2.6,(i/100-.5)*5])}else if(kind==='Bezier'&&cp.length>=4)for(let i=0;i<=96;i++){const t=i/96;out.push([bez(cp[0][0],cp[1][0],cp[2][0],cp[3][0],t),bez(cp[0][1],cp[1][1],cp[2][1],cp[3][1],t)])}else{for(let i=0;i<=96;i++){const t=i/96*(P.closed?cp.length:cp.length-1),j=Math.floor(t),u=t-j,a=cp[(j-1+cp.length)%cp.length],b=cp[j%cp.length],c=cp[(j+1)%cp.length],d=cp[(j+2)%cp.length],ten=P.curveKind==='NURBS'?.7:(P.tension??.5),u2=u*u,u3=u2*u;out.push([b[0]+(-ten*a[0]+ten*c[0])*u+(2*ten*a[0]+(ten-3)*b[0]+(3-2*ten)*c[0]-ten*d[0])*u2+(-ten*a[0]+(2-ten)*b[0]+(ten-2)*c[0]+ten*d[0])*u3,b[1]+(-ten*a[1]+ten*c[1])*u+(2*ten*a[1]+(ten-3)*b[1]+(3-2*ten)*c[1]-ten*d[1])*u2+(-ten*a[1]+(2-ten)*b[1]+(ten-2)*c[1]+ten*d[1])*u3])}}return out};
 const length=()=>{const s=sample();let n=0;for(let i=1;i<s.length;i++)n+=Math.hypot(s[i][0]-s[i-1][0],s[i][1]-s[i-1][1]);return n*Math.max(scale()[0],scale()[1])};
 const hero=el('div','pcard mp-hero cu-hero'),cv=el('canvas'),cap=el('div','mp-cap',`<div class="l"><b>Curve editor</b><span class="mp-illum cu-sub">CONTROL HULL · LOCAL XY</span></div><div class="r">—</div>`);hero.append(cv,cap);host.append(hero);let drag=-1;
 function paintHero(){const[g,w,h]=canvas(cv,compact?150:182),cp=P.controlPoints,s=sample(),map=p=>[w/2+p[0]/10*w*.82,h/2-p[1]/7*h*.76];g.clearRect(0,0,w,h);g.fillStyle='#050505';g.fillRect(0,0,w,h);for(let i=-5;i<=5;i++){g.strokeStyle=i?'rgba(255,255,255,.055)':'rgba(255,255,255,.15)';g.beginPath();g.moveTo(w/2+i*w/10,8);g.lineTo(w/2+i*w/10,h-8);g.moveTo(8,h/2+i*h/8);g.lineTo(w-8,h/2+i*h/8);g.stroke()}if(P.showControls&& !['Arc','Helix'].includes(P.curveKind)){g.strokeStyle='rgba(255,255,255,.26)';g.setLineDash([3,3]);g.beginPath();cp.forEach((p,i)=>{const q=map(p);i?g.lineTo(...q):g.moveTo(...q)});g.stroke();g.setLineDash([])}g.beginPath();s.forEach((p,i)=>{const q=map(p);i?g.lineTo(...q):g.moveTo(...q)});if(P.closed)g.closePath();g.strokeStyle=P.color;g.lineWidth=Math.min(5,P.thickness);g.stroke();g.lineWidth=1;if(!['Arc','Helix'].includes(P.curveKind))cp.forEach((p,i)=>{const q=map(p);g.fillStyle=i===drag?'#fff':P.color;g.beginPath();g.arc(...q,i===0||i===cp.length-1?5:4,0,Math.PI*2);g.fill();g.strokeStyle='#050505';g.stroke()});g.fillStyle='rgba(255,255,255,.34)';g.font='8px ui-sans-serif';g.fillText('−X',8,h/2-5);g.textAlign='right';g.fillText('+X',w-8,h/2-5);cap.querySelector('.cu-sub').textContent=`${P.pointCount} controls · degree ${P.degree} · ${P.adaptive?'adaptive':'fixed'} sampling`;cap.querySelector('.r').textContent=`${length().toFixed(1)} m`}
 const hit=e=>{const r=cv.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width*.82)*10,y=-(e.clientY-r.top-r.height/2)/(r.height*.76)*7;let best=-1,bd=.45;P.controlPoints.forEach((p,i)=>{const d=Math.hypot(p[0]-x,p[1]-y);if(d<bd){bd=d;best=i}});return{best,x,y}};cv.onpointerdown=e=>{const q=hit(e);drag=q.best;if(drag>=0){cv.setPointerCapture(e.pointerId);cv.classList.add('grabbing')}};cv.onpointermove=e=>{if(drag<0||!cv.hasPointerCapture?.(e.pointerId))return;const q=hit(e),a=P.controlPoints.map(p=>[...p]);a[drag][0]=clamp(q.x,-5,5);a[drag][1]=clamp(q.y,-3.5,3.5);setProp(node,'controlPoints',a);paintAll()};cv.onpointerup=()=>{drag=-1;cv.classList.remove('grabbing');paintHero()};
 const rail=el('div','mp-rail');const metric=k=>{const e=el('div','mp-pill',`<b class="v">—</b><span class="k">${k}</span>`);rail.append(e);return e.querySelector('.v')};const mType=metric('Type'),mLen=metric('Length'),mPts=metric('Points'),mDeg=metric('Degree');host.append(rail);
 const tc=el('div','pcard mp-light cu-types');tc.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Curve basis</span><span class="s">Interpolation family</span></div></div>`;const tb=el('div','pbody'),kindTags=el('div','mp-tags cu-kinds');kinds.forEach(k=>{const b=el('button',`mp-tag${P.curveKind===k?' on':''}`,k.toUpperCase());b.onclick=()=>{setProp(node,'curveKind',k);paintAll()};kindTags.append(b)});tb.append(kindTags);const note=el('div','mp-note');tb.append(note);tc.append(tb);host.append(tc);
 const gc=el('div','pcard mp-light cu-geometry');gc.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Geometry</span><span class="s">Control count · continuity · display</span></div></div>`;const gb=el('div','pbody');gc.append(gb);const points=tape({label:'Control points',min:2,max:32,value:P.pointCount,dec:0,step:1,marks:[{t:0,l:'2'},{t:.067,l:'4'},{t:1,l:'32'}],onInput:v=>{const n=Math.round(v);setProp(node,'pointCount',n);setProp(node,'controlPoints',defaultPoints(n));paintAll()}}),degree=tape({label:'Polynomial degree',min:1,max:5,value:P.degree,dec:0,step:1,marks:[{t:0,l:'LINEAR 1'},{t:.5,l:'CUBIC 3'},{t:1,l:'QUINTIC 5'}],onInput:v=>{setProp(node,'degree',Math.round(v));paintAll()}}),tension=tape({label:'Spline tension',min:0,max:1,value:P.tension,dec:2,step:.01,marks:[{t:0,l:'LOOSE'},{t:.5,l:'.50'},{t:1,l:'TAUT'}],onInput:v=>{setProp(node,'tension',v);paintAll()}}),width=tape({label:'Viewport width',min:.5,max:8,value:P.thickness,dec:1,step:.1,unit:'px',marks:[{t:0,l:'HAIRLINE'},{t:.2,l:'2 px'},{t:1,l:'8 px'}],onInput:v=>{setProp(node,'thickness',v);paintAll()}});gb.append(points,degree,tension,width);const ch=el('div','mp-subhead','<span class="k">curve colour</span>'),chip=colorChip(P.color,v=>{setProp(node,'color',v);paintAll()});ch.append(chip);gb.append(ch);const tags=el('div','mp-tags'),closed=pillToggle('CLOSED LOOP',P.closed,v=>{setProp(node,'closed',v);paintAll()}),controls=pillToggle('CONTROL HULL',P.showControls!==false,v=>{setProp(node,'showControls',v);paintAll()}),adaptive=pillToggle('ADAPTIVE',P.adaptive!==false,v=>{setProp(node,'adaptive',v);paintAll()});tags.append(closed,controls,adaptive);gb.append(tags);host.append(gc);
 const pc=el('div','pcard mp-light cu-transform');pc.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Transform</span><span class="s">Curve object space</span></div></div>`;const pb=el('div','pbody'),syncs=[];pc.append(pb);const addVec=(label,key,get,unit)=>{const h=el('div','mp-subhead',`<span class="k">${label}</span>`),r=el('div','cu-steppers');['X','Y','Z'].forEach((k,i)=>{const x=el('div','cu-axis',`<span>${k}</span>`),s=stepper({value:get()[i],min:key==='scale'?.01:-999,max:999,dec:2,step:key==='rot'?1:.05,unit:i===0?unit:'',onInput:v=>{const a=[...get()];a[i]=v;setProp(node,key,a);paintAll()}});x.append(s);x._step=s;r.append(x)});pb.append(h,r);syncs.push(()=>[...r.children].forEach((x,i)=>x._step._set(get()[i])))};addVec('position','pos',pos,'m');addVec('rotation','rot',rot,'°');addVec('scale','scale',scale,'×');host.append(pc);
 function paintAll(){paintHero();mType.textContent=P.curveKind.replace('Catmull-','C-');mLen.innerHTML=`${length().toFixed(1)}<em>m</em>`;mPts.textContent=P.pointCount;mDeg.textContent=P.degree;[...kindTags.children].forEach((b,i)=>b.classList.toggle('on',kinds[i]===P.curveKind));[points,degree,tension,width].forEach((t,i)=>t._set([P.pointCount,P.degree,P.tension,P.thickness][i]));chip._set?.(P.color);closed._set(P.closed);controls._set(P.showControls);adaptive._set(P.adaptive);note.textContent=({Bezier:'Endpoint interpolation with explicit handles.', 'Catmull-Rom':'Smooth path passing through every control point.',NURBS:'Degree-controlled non-uniform smooth basis.',Polyline:'Straight segments through control points.',Arc:'Analytic circular segment or closed ring.',Helix:'Parametric helical path for coils and motion.'})[P.curveKind];syncs.forEach(f=>f())}
 register?.(paintAll);const ro=new ResizeObserver(()=>{paintHero();[points,degree,tension,width].forEach(t=>t._paint?.())});ro.observe(host);host._dispose=()=>ro.disconnect();requestAnimationFrame(paintAll);paintAll();return host;
}
