/* Bespoke instruments for particles, reflection probes, spatial audio and the post stack. */
import { el, colorChip } from '../kit.js';
import { tape, stepper, pillToggle } from './controls.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rgb=c=>{const n=parseInt((c||'#ffffff').slice(1),16);return[n>>16&255,n>>8&255,n&255]};
const css=(c,a=1)=>`rgba(${c.map(Math.round).join(',')},${a})`;
const canvas=(cv,h)=>{const w=cv.clientWidth||290,d=Math.min(devicePixelRatio||1,2);if(cv.width!==w*d||cv.height!==h*d){cv.width=w*d;cv.height=h*d}cv.style.height=h+'px';const g=cv.getContext('2d');g.setTransform(d,0,0,d,0,0);return[g,w,h]};
const card=(title,sub,cls='')=>{const c=el('div',`pcard mp-light ${cls}`);c.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">${title}</span><span class="s">${sub}</span></div></div>`;const b=el('div','pbody');c.append(b);c.querySelector('.mp-chead .l').onclick=()=>c.classList.toggle('shut');return[c,b]};
const addVec=(body,label,key,get,node,setProp,paint)=>{const h=el('div','mp-subhead',`<span class="k">${label}</span>`),r=el('div','ef-steppers');['X','Y','Z'].forEach((k,i)=>{const x=el('div','ef-axis',`<span>${k}</span>`),s=stepper({value:get()[i],min:-999,max:999,dec:2,step:.05,unit:i===0?'m':'',onInput:v=>{const a=[...get()];a[i]=v;setProp(node,key,a);paint()}});x.append(s);x._step=s;r.append(x)});body.append(h,r);return()=>[...r.children].forEach((x,i)=>x._step._set(get()[i]))};

export function effectsPanel(node,ctx){if(node.type==='particles')return particles(node,ctx);if(node.type==='probe')return probe(node,ctx);if(node.type==='audio')return audio(node,ctx);return post(node,ctx)}

function particles(node,{compact=false,setProp,register}){
 const P=node.props,host=el('div','mpanel effectpanel particlepanel'),pos=()=>P.pos||[0,0,0];
 const hero=el('div','pcard mp-hero ef-hero'),cv=el('canvas'),cap=el('div','mp-cap',`<div class="l"><b>Particle field</b><span class="mp-illum ef-sub">EMITTER VOLUME</span></div><div class="r">—</div>`);hero.append(cv,cap);host.append(hero);let phase=0,raf=0,alive=true;
 function paintHero(){const[g,w,h]=canvas(cv,compact?145:174),c=rgb(P.color),n=Math.min(420,Math.max(8,Math.floor((P.count??420)/8))),rad=P.radius??7,hei=P.height??4.2;g.clearRect(0,0,w,h);g.fillStyle='#040404';g.fillRect(0,0,w,h);g.strokeStyle='rgba(255,255,255,.1)';g.strokeRect(w*.12,h*.12,w*.76,h*.7);for(let i=0;i<n;i++){const seed=(Math.sin(i*91.7)*43758.5)%1,x=((seed+1)%1-.5)*rad/40*w*.7+w/2,life=((i*.618+phase*(P.speed??.5))%1+1)%1,y=h*.82-life*(.28+.72*hei/30)*h*.66,f=.4+.6*Math.sin(phase*4+i*2.7)*(P.flicker??.7);g.fillStyle=css(c,.18+.7*Math.abs(f));g.fillRect(x,y,Math.max(1,P.size??1.5),Math.max(1,P.size??1.5))}g.font='8px ui-sans-serif';g.fillStyle='rgba(255,255,255,.3)';g.fillText(`${rad.toFixed(1)} m SPREAD`,8,h-7);g.textAlign='right';g.fillText(`${hei.toFixed(1)} m COLUMN`,w-8,h-7);cap.querySelector('.r').textContent=`${(P.count??420).toFixed(0)} particles`}
 function tick(){if(!alive)return;phase+=.012;paintHero();raf=requestAnimationFrame(tick)}
 const rail=el('div','mp-rail');const m=k=>{const e=el('div','mp-pill',`<b class="v">—</b><span class="k">${k}</span>`);rail.append(e);return e.querySelector('.v')},mCount=m('Count'),mRate=m('Rise'),mLife=m('Column'),mFill=m('Density');host.append(rail);
 const[ec,eb]=card('Emitter','Population · spatial envelope','ef-emitter');const count=tape({label:'Particle count',min:0,max:4000,value:P.count,dec:0,step:20,marks:[{t:0,l:'EMPTY'},{t:.105,l:'420'},{t:1,l:'4 000'}],onInput:v=>{setProp(node,'count',Math.round(v));paintAll()}}),spread=tape({label:'Radial spread',min:.5,max:40,value:P.radius,dec:1,step:.5,unit:'m',onInput:v=>{setProp(node,'radius',v);paintAll()}}),height=tape({label:'Column height',min:.2,max:30,value:P.height,dec:1,step:.2,unit:'m',onInput:v=>{setProp(node,'height',v);paintAll()}});eb.append(count,spread,height);host.append(ec);
 const[lc,lb]=card('Particle appearance','Point response · temporal motion','ef-look');const size=tape({label:'Point size',min:.2,max:8,value:P.size,dec:2,step:.1,unit:'px',marks:[{t:0,l:'DUST'},{t:.167,l:'1.5 px'},{t:1,l:'ORB'}],onInput:v=>{setProp(node,'size',v);paintAll()}}),speed=tape({label:'Rise speed',min:0,max:3,value:P.speed,dec:2,step:.05,unit:'×',marks:[{t:0,l:'STILL'},{t:.167,l:'.50×'},{t:1,l:'3×'}],onInput:v=>{setProp(node,'speed',v);paintAll()}}),flicker=tape({label:'Flicker',min:0,max:1,value:P.flicker,dec:2,step:.01,marks:[{t:0,l:'STEADY'},{t:.7,l:'FIREFLY'},{t:1,l:'STROBE'}],onInput:v=>{setProp(node,'flicker',v);paintAll()}});lb.append(size,speed,flicker);const ch=el('div','mp-subhead','<span class="k">particle colour</span>'),chip=colorChip(P.color,v=>{setProp(node,'color',v);paintAll()});ch.append(chip);lb.append(ch);host.append(lc);
 const[pc,pb]=card('Emitter placement','World coordinates','ef-place'),syncPos=addVec(pb,'origin','pos',pos,node,setProp,paintAll);host.append(pc);
 function paintAll(){paintHero();mCount.textContent=P.count.toFixed(0);mRate.innerHTML=`${P.speed.toFixed(2)}<em>×</em>`;mLife.innerHTML=`${P.height.toFixed(1)}<em>m</em>`;mFill.innerHTML=`${(P.count/(Math.PI*P.radius*P.radius*P.height)).toFixed(1)}<em>/m³</em>`;[count,spread,height,size,speed,flicker].forEach((t,i)=>t._set([P.count,P.radius,P.height,P.size,P.speed,P.flicker][i]));chip._set?.(P.color);syncPos()}
 register?.(paintAll);const ro=new ResizeObserver(()=>{paintHero();[count,spread,height,size,speed,flicker].forEach(t=>t._paint?.())});ro.observe(host);host._dispose=()=>{alive=false;cancelAnimationFrame(raf);ro.disconnect()};requestAnimationFrame(tick);paintAll();return host;
}

function probe(node,{compact=false,setProp,register}){
 const P=node.props,host=el('div','mpanel effectpanel probepanel'),pos=()=>P.pos||[0,0,0];
 const hero=el('div','pcard mp-hero ef-hero'),cv=el('canvas'),cap=el('div','mp-cap',`<div class="l"><b>Reflection capture</b><span class="mp-illum ef-sub">CUBEMAP PROJECTION</span></div><div class="r">—</div>`);hero.append(cv,cap);host.append(hero);
 function paintHero(){const[g,w,h]=canvas(cv,compact?145:174),c=rgb('#7de0ff'),s=Math.min(w/4,h/3),x=w/2-s*1.5,y=h/2-s*.5;g.clearRect(0,0,w,h);g.fillStyle='#040404';g.fillRect(0,0,w,h);const faces=[['+X',1,1],['−X',-1,1],['+Y',0,0],['−Y',0,2],['+Z',0,1],['−Z',2,1]];faces.forEach(([n,dx,dy],i)=>{const xx=x+dx*s,yy=y+dy*s,gr=g.createLinearGradient(xx,yy,xx+s,yy+s);gr.addColorStop(0,css(c,.08+i*.025));gr.addColorStop(1,`rgba(${30+i*18},${18+i*10},${42+i*12},.8)`);g.fillStyle=gr;g.fillRect(xx,yy,s-2,s-2);g.strokeStyle='rgba(255,255,255,.18)';g.strokeRect(xx+.5,yy+.5,s-3,s-3);g.fillStyle='rgba(255,255,255,.45)';g.font='8px ui-sans-serif';g.fillText(n,xx+5,yy+11)});cap.querySelector('.r').textContent=`${P.resolution}² capture`}
 const rail=el('div','mp-rail');const m=k=>{const e=el('div','mp-pill',`<b class="v">—</b><span class="k">${k}</span>`);rail.append(e);return e.querySelector('.v')},mRad=m('Radius'),mVol=m('Volume'),mRes=m('Face'),mMode=m('Mode');host.append(rail);
 const[ic,ib]=card('Influence volume','Spherical blend domain','ef-influence'),sphere=el('div','mp-meter ef-sphere','<div class="hd"><span class="k">radial influence section</span></div>'),scv=el('canvas');sphere.append(scv);ib.append(sphere);const radius=tape({label:'Capture radius',min:1,max:80,value:P.radius,dec:1,step:.5,unit:'m',marks:[{t:0,l:'1 m'},{t:.165,l:'14 m'},{t:1,l:'80 m'}],onInput:v=>{setProp(node,'radius',v);paintAll()}}),intensity=tape({label:'Reflection intensity',min:0,max:3,value:P.intensity,dec:2,step:.05,unit:'×',marks:[{t:0,l:'OFF'},{t:.333,l:'REAL 1×'},{t:1,l:'3×'}],onInput:v=>{setProp(node,'intensity',v);paintAll()}});ib.append(radius,intensity);host.append(ic);
 function paintSphere(){const[g,w,h]=canvas(scv,105),cx=w/2,cy=h/2,r=40;g.clearRect(0,0,w,h);const gr=g.createRadialGradient(cx,cy,0,cx,cy,r);gr.addColorStop(0,'rgba(125,224,255,.34)');gr.addColorStop(1,'rgba(125,224,255,.02)');g.fillStyle=gr;g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.fill();g.strokeStyle='rgba(125,224,255,.75)';g.stroke();[.25,.5,.75].forEach(f=>{g.strokeStyle='rgba(255,255,255,.1)';g.beginPath();g.arc(cx,cy,r*f,0,Math.PI*2);g.stroke()});g.fillStyle='rgba(255,255,255,.35)';g.font='8px ui-sans-serif';g.textAlign='center';g.fillText(`${P.radius.toFixed(1)} m`,cx,cy+3)}
 const[cc,cb]=card('Capture','Resolution · update policy','ef-capture'),res=el('div','mp-tags ef-res');['128','256','512','1024'].forEach(v=>{const b=el('button',`mp-tag${P.resolution===v?' on':''}`,`${v}²`);b.onclick=()=>{setProp(node,'resolution',v);paintAll()};res.append(b)});cb.append(res);const tags=el('div','mp-tags'),real=pillToggle('REALTIME',!!P.realtime,v=>{setProp(node,'realtime',v);paintAll()}),bounds=pillToggle('DRAW BOUNDS',P.showBounds!==false,v=>{setProp(node,'showBounds',v);paintAll()});tags.append(real,bounds);cb.append(tags);host.append(cc);
 const[pc,pb]=card('Probe placement','World coordinates','ef-place'),syncPos=addVec(pb,'capture origin','pos',pos,node,setProp,paintAll);host.append(pc);
 function paintAll(){paintHero();paintSphere();mRad.innerHTML=`${P.radius.toFixed(1)}<em>m</em>`;mVol.innerHTML=`${(4/3*Math.PI*P.radius**3/1000).toFixed(1)}<em>km³</em>`;mRes.textContent=P.resolution;mMode.textContent=P.realtime?'LIVE':'BAKED';radius._set(P.radius);intensity._set(P.intensity);real._set(P.realtime);bounds._set(P.showBounds!==false);[...res.children].forEach((b,i)=>b.classList.toggle('on',['128','256','512','1024'][i]===P.resolution));syncPos()}
 register?.(paintAll);const ro=new ResizeObserver(()=>{paintHero();paintSphere();radius._paint?.();intensity._paint?.()});ro.observe(host);host._dispose=()=>ro.disconnect();requestAnimationFrame(paintAll);paintAll();return host;
}

function audio(node,{compact=false,setProp,register}){
 const P=node.props,host=el('div','mpanel effectpanel audiopanel'),pos=()=>P.pos||[0,0,0],clips=['Shoreline','Wind in pines','Night insects','Distant thunder'];
 const hero=el('div','pcard mp-hero ef-hero'),cv=el('canvas'),cap=el('div','mp-cap',`<div class="l"><b>Spatial audio</b><span class="mp-illum ef-sub">WAVEFORM · 12 S</span></div><div class="r">—</div>`);hero.append(cv,cap);host.append(hero);
 function paintHero(){const[g,w,h]=canvas(cv,compact?145:174),cy=h/2,amp=(P.gain??.8)*h*.28;g.clearRect(0,0,w,h);g.fillStyle='#040404';g.fillRect(0,0,w,h);g.strokeStyle='rgba(183,141,255,.85)';g.beginPath();for(let x=0;x<w;x++){const t=x/w*18,y=cy+(Math.sin(t*2.1)+.45*Math.sin(t*5.7)+.2*Math.sin(t*13.3))*amp*.5*(.5+.5*Math.sin(t*.23+1));x?g.lineTo(x,y):g.moveTo(x,y)}g.stroke();g.strokeStyle='rgba(255,255,255,.1)';g.beginPath();g.moveTo(0,cy);g.lineTo(w,cy);g.stroke();for(let x=0;x<w;x+=w/12){g.strokeStyle='rgba(255,255,255,.05)';g.beginPath();g.moveTo(x,0);g.lineTo(x,h);g.stroke()}cap.querySelector('.r').textContent=`${P.gain.toFixed(2)}× gain`}
 const rail=el('div','mp-rail');const m=k=>{const e=el('div','mp-pill',`<b class="v">—</b><span class="k">${k}</span>`);rail.append(e);return e.querySelector('.v')},mGain=m('Gain'),mRad=m('Falloff'),mDb=m('Edge'),mMode=m('Mode');host.append(rail);
 const[fc,fb]=card('Spatial falloff','Inverse-distance listening field','ef-falloff'),polar=el('div','mp-meter ef-polar','<div class="hd"><span class="k">audibility field</span></div>'),pcv=el('canvas');polar.append(pcv);fb.append(polar);const gain=tape({label:'Source gain',min:0,max:2,value:P.gain,dec:2,step:.02,unit:'×',marks:[{t:0,l:'MUTE'},{t:.4,l:'.80×'},{t:1,l:'2×'}],onInput:v=>{setProp(node,'gain',v);paintAll()}}),radius=tape({label:'Falloff radius',min:1,max:200,value:P.radius,dec:0,step:1,unit:'m',marks:[{t:0,l:'1 m'},{t:.156,l:'32 m'},{t:1,l:'200 m'}],onInput:v=>{setProp(node,'radius',Math.round(v));paintAll()}});fb.append(gain,radius);host.append(fc);
 function paintPolar(){const[g,w,h]=canvas(pcv,112),cx=w/2,cy=h/2,r=45;g.clearRect(0,0,w,h);for(let i=10;i>=1;i--){const f=i/10,a=(1-f)*.35*P.gain;g.fillStyle=`rgba(183,141,255,${a})`;g.beginPath();g.arc(cx,cy,r*f,0,Math.PI*2);g.fill()}[.25,.5,.75,1].forEach(f=>{g.strokeStyle='rgba(255,255,255,.1)';g.beginPath();g.arc(cx,cy,r*f,0,Math.PI*2);g.stroke()});g.fillStyle='#fff';g.beginPath();g.arc(cx,cy,3,0,Math.PI*2);g.fill();g.fillStyle='rgba(255,255,255,.3)';g.font='8px ui-sans-serif';g.textAlign='center';g.fillText(`${P.radius} m`,cx,cy-r-4)}
 const[sc,sb]=card('Source','Clip · playback policy','ef-source'),clipTags=el('div','mp-tags ef-clips');clips.forEach(v=>{const b=el('button',`mp-tag${P.clip===v?' on':''}`,v.toUpperCase());b.onclick=()=>{setProp(node,'clip',v);paintAll()};clipTags.append(b)});sb.append(clipTags);const tags=el('div','mp-tags'),loop=pillToggle('LOOP',P.loop!==false,v=>{setProp(node,'loop',v);paintAll()}),spatial=pillToggle('3D SPATIAL',P.spatial!==false,v=>{setProp(node,'spatial',v);paintAll()});tags.append(loop,spatial);sb.append(tags);host.append(sc);
 const[pl,pb]=card('Emitter placement','World coordinates','ef-place'),syncPos=addVec(pb,'source origin','pos',pos,node,setProp,paintAll);host.append(pl);
 function paintAll(){paintHero();paintPolar();mGain.innerHTML=`${P.gain.toFixed(2)}<em>×</em>`;mRad.innerHTML=`${P.radius}<em>m</em>`;mDb.innerHTML=`${(-20*Math.log10(Math.max(1,P.radius))).toFixed(0)}<em>dB</em>`;mMode.textContent=P.spatial?'3D':'2D';gain._set(P.gain);radius._set(P.radius);loop._set(P.loop);spatial._set(P.spatial);[...clipTags.children].forEach((b,i)=>b.classList.toggle('on',clips[i]===P.clip));syncPos()}
 register?.(paintAll);const ro=new ResizeObserver(()=>{paintHero();paintPolar();gain._paint?.();radius._paint?.()});ro.observe(host);host._dispose=()=>ro.disconnect();requestAnimationFrame(paintAll);paintAll();return host;
}

function post(node,{compact=false,setProp,register}){
 const P=node.props,host=el('div','mpanel effectpanel postpanel'),maps=['ACES','AgX','Filmic','Reinhard','Linear'];
 const hero=el('div','pcard mp-hero ef-hero'),cv=el('canvas'),cap=el('div','mp-cap',`<div class="l"><b>Final image</b><span class="mp-illum ef-sub">BEFORE / AFTER</span></div><div class="r">—</div>`);hero.append(cv,cap);host.append(hero);
 function paintHero(){const[g,w,h]=canvas(cv,compact?145:174);g.clearRect(0,0,w,h);for(let x=0;x<w;x++)for(let y=0;y<h;y+=3){let v=x/w*1.25,after=x>w/2;v*=after?P.exposure:1;if(after){v=(v-.5)*(P.contrast??1.02)+.5;v=Math.pow(clamp(v,0,1),P.tonemap==='Linear'?1:P.tonemap==='Reinhard'?.7:.82)}const sat=after?P.saturation:1,r=clamp(v*(.75+.25*sat),0,1),gg=clamp(v*(.85+.15*sat),0,1),b=clamp(v*(1.1-.1*sat),0,1);g.fillStyle=`rgb(${r*255},${gg*255},${b*255})`;g.fillRect(x,y,1,3)}g.strokeStyle='#fff';g.beginPath();g.moveTo(w/2,0);g.lineTo(w/2,h);g.stroke();g.fillStyle='rgba(255,255,255,.65)';g.font='8px ui-sans-serif';g.fillText('SOURCE',8,13);g.textAlign='right';g.fillText('GRADED',w-8,13);const vig=P.vignette??.32,gr=g.createRadialGradient(w*.75,h/2,h*.15,w*.75,h/2,h*.65);gr.addColorStop(0,'rgba(0,0,0,0)');gr.addColorStop(1,`rgba(0,0,0,${vig})`);g.fillStyle=gr;g.fillRect(w/2,0,w/2,h);cap.querySelector('.r').textContent=`${P.tonemap} · ${P.exposure.toFixed(2)} EV`}
 const rail=el('div','mp-rail');const m=k=>{const e=el('div','mp-pill',`<b class="v">—</b><span class="k">${k}</span>`);rail.append(e);return e.querySelector('.v')},mExp=m('Exposure'),mCon=m('Contrast'),mSat=m('Saturation'),mBloom=m('Bloom');host.append(rail);
 const[tc,tb]=card('Tone response','Transfer curve · display mapping','ef-tone'),curve=el('div','mp-meter ef-curve','<div class="hd"><span class="k">input luminance → display</span></div>'),tcv=el('canvas');curve.append(tcv);tb.append(curve);const exp=tape({label:'Exposure',min:.05,max:4,value:P.exposure,dec:2,step:.05,unit:'EV',marks:[{t:0,l:'DARK'},{t:.24,l:'1 EV'},{t:1,l:'4 EV'}],onInput:v=>{setProp(node,'exposure',v);paintAll()}}),con=tape({label:'Contrast',min:.5,max:2,value:P.contrast,dec:2,step:.02,marks:[{t:0,l:'FLAT'},{t:.347,l:'1.02'},{t:1,l:'HARD'}],onInput:v=>{setProp(node,'contrast',v);paintAll()}}),sat=tape({label:'Saturation',min:0,max:2,value:P.saturation,dec:2,step:.02,marks:[{t:0,l:'MONO'},{t:.5,l:'REAL 1'},{t:1,l:'2×'}],onInput:v=>{setProp(node,'saturation',v);paintAll()}});tb.append(exp,con,sat);const mapTags=el('div','mp-tags ef-maps');maps.forEach(v=>{const b=el('button',`mp-tag${P.tonemap===v?' on':''}`,v.toUpperCase());b.onclick=()=>{setProp(node,'tonemap',v);paintAll()};mapTags.append(b)});tb.append(mapTags);host.append(tc);
 function paintCurve(){const[g,w,h]=canvas(tcv,112),pad=9;g.clearRect(0,0,w,h);g.strokeStyle='rgba(255,255,255,.08)';for(let i=0;i<=4;i++){const x=pad+i/4*(w-pad*2),y=pad+i/4*(h-pad*2);g.beginPath();g.moveTo(x,pad);g.lineTo(x,h-pad);g.moveTo(pad,y);g.lineTo(w-pad,y);g.stroke()}g.beginPath();for(let i=0;i<=100;i++){const x=i/100,v=(x*P.exposure-.5)*P.contrast+.5,y=P.tonemap==='Linear'?v:v/(1+Math.max(0,v)*.35);i?g.lineTo(pad+x*(w-pad*2),h-pad-clamp(y,0,1)*(h-pad*2)):g.moveTo(pad,h-pad)}g.strokeStyle='rgba(255,255,255,.9)';g.lineWidth=1.5;g.stroke();g.lineWidth=1}
 const[ic,ib]=card('Image texture','Bloom · vignette · grain','ef-image'),bloomStrength=tape({label:'Bloom strength',min:0,max:2,value:P.bloomStrength,dec:2,step:.02,marks:[{t:0,l:'OFF'},{t:.21,l:'.42'},{t:1,l:'HALO'}],onInput:v=>{setProp(node,'bloomStrength',v);paintAll()}}),threshold=tape({label:'Bloom threshold',min:0,max:2,value:P.bloomThreshold,dec:2,step:.02,marks:[{t:0,l:'ALL'},{t:.425,l:'.85'},{t:1,l:'HIGHLIGHTS'}],onInput:v=>{setProp(node,'bloomThreshold',v);paintAll()}}),vignette=tape({label:'Vignette',min:0,max:1,value:P.vignette,dec:2,step:.01,marks:[{t:0,l:'NONE'},{t:.32,l:'.32'},{t:1,l:'TUNNEL'}],onInput:v=>{setProp(node,'vignette',v);paintAll()}}),grain=tape({label:'Film grain',min:0,max:1,value:P.grain,dec:2,step:.01,marks:[{t:0,l:'CLEAN'},{t:.12,l:'.12'},{t:1,l:'COARSE'}],onInput:v=>{setProp(node,'grain',v);paintAll()}});ib.append(bloomStrength,threshold,vignette,grain);const tags=el('div','mp-tags'),bloom=pillToggle('BLOOM',P.bloom!==false,v=>{setProp(node,'bloom',v);paintAll()});tags.append(bloom);ib.append(tags);host.append(ic);
 function paintAll(){paintHero();paintCurve();mExp.innerHTML=`${P.exposure.toFixed(2)}<em>EV</em>`;mCon.textContent=P.contrast.toFixed(2);mSat.textContent=P.saturation.toFixed(2);mBloom.textContent=P.bloom?'ON':'OFF';[exp,con,sat,bloomStrength,threshold,vignette,grain].forEach((t,i)=>t._set([P.exposure,P.contrast,P.saturation,P.bloomStrength,P.bloomThreshold,P.vignette,P.grain][i]));bloom._set(P.bloom);[...mapTags.children].forEach((b,i)=>b.classList.toggle('on',maps[i]===P.tonemap))}
 register?.(paintAll);const ro=new ResizeObserver(()=>{paintHero();paintCurve();[exp,con,sat,bloomStrength,threshold,vignette,grain].forEach(t=>t._paint?.())});ro.observe(host);host._dispose=()=>ro.disconnect();requestAnimationFrame(paintAll);paintAll();return host;
}
