/* Terrain authoring instrument: topographic atlas, relief section, source and surface controls. */
import { el, colorChip } from '../kit.js';
import { tape, stepper, pillToggle } from './controls.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rgb=c=>{const n=parseInt((c||'#263628').slice(1),16);return[n>>16&255,n>>8&255,n&255]};
const css=(c,a=1)=>`rgba(${c.map(Math.round).join(',')},${a})`;
const field=(x,y,seed,f)=>clamp(.5+.23*Math.sin((x*5.3+seed*.013)*f)+.16*Math.sin((y*7.1-seed*.019)*f)+.09*Math.sin((x+y)*15.7*f),0,1);
export function terrainPanel(node,ctx){
 const{compact=false,setProp,register}=ctx,P=node.props,host=el('div','mpanel terrainpanel'),pos=()=>P.pos||[0,0,0];
 const canvas=(cv,h)=>{const w=cv.clientWidth||290,d=Math.min(devicePixelRatio||1,2);if(cv.width!==w*d||cv.height!==h*d){cv.width=w*d;cv.height=h*d}cv.style.height=h+'px';const g=cv.getContext('2d');g.setTransform(d,0,0,d,0,0);return[g,w,h]};
 const hero=el('div','pcard mp-hero te-hero'),cv=el('canvas');cv.title='Drag across for feature scale; vertically for relief';const cap=el('div','mp-cap',`<div class="l"><b>Topographic field</b><span class="mp-illum te-sub">PROCEDURAL HEIGHT SOURCE</span></div><div class="r">—</div>`);hero.append(cv,cap);host.append(hero);let mark=null;
 function paintHero(){const[g,w,h]=canvas(cv,compact?148:178),lo=rgb(P.lowColor),hi=rgb(P.highColor),step=3;g.clearRect(0,0,w,h);for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const n=field(x/w,y/h,P.seed,P.frequency),c=lo.map((v,i)=>v+(hi[i]-v)*n);g.fillStyle=css(c);g.fillRect(x,y,step+.2,step+.2)}
  /* contours */for(let level=.15;level<1;level+=.12){g.strokeStyle='rgba(255,255,255,.18)';g.beginPath();let open=false;for(let x=0;x<w;x+=2){let best=0,err=9;for(let y=0;y<h;y+=2){const e=Math.abs(field(x/w,y/h,P.seed,P.frequency)-level);if(e<err){err=e;best=y}}if(err<.025){open?g.lineTo(x,best):g.moveTo(x,best);open=true}else open=false}g.stroke()}
  g.strokeStyle='rgba(255,255,255,.14)';for(let x=0;x<w;x+=w/8){g.beginPath();g.moveTo(x,0);g.lineTo(x,h);g.stroke()}for(let y=0;y<h;y+=h/5){g.beginPath();g.moveTo(0,y);g.lineTo(w,y);g.stroke()}g.fillStyle='rgba(255,255,255,.42)';g.font='8px ui-sans-serif';g.fillText('N',8,13);g.textAlign='right';g.fillText(`${P.size.toFixed(0)} × ${P.size.toFixed(0)} m`,w-8,13);if(mark){g.strokeStyle='#fff';g.setLineDash([2,3]);g.beginPath();g.moveTo(mark.x,0);g.lineTo(mark.x,h);g.moveTo(0,mark.y);g.lineTo(w,mark.y);g.stroke();g.setLineDash([])}cap.querySelector('.te-sub').textContent=`seed ${P.seed} · ${P.resolution}² samples · ${P.frequency.toFixed(2)}× features`;cap.querySelector('.r').textContent=`${P.height.toFixed(1)} m relief`}
 const heroFrom=e=>{const r=cv.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width,0,1),y=clamp((e.clientY-r.top)/r.height,0,1);mark={x:x*r.width,y:y*r.height};setProp(node,'frequency',+(.1+x*7.9).toFixed(2));setProp(node,'height',+((1-y)*80).toFixed(1));paintAll()};cv.onpointerdown=e=>{cv.setPointerCapture(e.pointerId);cv.classList.add('grabbing');heroFrom(e)};cv.onpointermove=e=>{if(cv.hasPointerCapture?.(e.pointerId))heroFrom(e)};cv.onpointerup=()=>{mark=null;cv.classList.remove('grabbing');paintHero()};
 const rail=el('div','mp-rail');const metric=k=>{const e=el('div','mp-pill',`<b class="v">—</b><span class="k">${k}</span>`);rail.append(e);return e.querySelector('.v')};const mArea=metric('Area'),mRelief=metric('Relief'),mCell=metric('Cell'),mSeed=metric('Seed');host.append(rail);
 const section=el('div','pcard mp-metric te-section');section.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Relief profile</span><span class="s">West–east section · datum referenced</span></div></div><div class="mp-num"><span class="i">—</span><span class="d"></span><span class="u">m</span></div><div class="mp-k mp-target">Maximum relief <span class="v">—</span></div>`;const sw=el('div','mp-chartwrap'),scv=el('canvas');sw.append(scv);section.append(sw);host.append(section);
 function paintSection(){const[g,w,h]=canvas(scv,112),base=h-17;g.clearRect(0,0,w,h);g.strokeStyle='rgba(255,255,255,.07)';[.25,.5,.75,1].forEach(t=>{const y=base-t*(h-26);g.beginPath();g.moveTo(7,y);g.lineTo(w-8,y);g.stroke()});g.beginPath();g.moveTo(7,base);for(let x=0;x<=w-15;x++){const n=field(x/(w-15),.5,P.seed,P.frequency),y=base-n*(h-28);g.lineTo(7+x,y)}g.lineTo(w-8,base);g.closePath();const gr=g.createLinearGradient(0,10,0,base);gr.addColorStop(0,css(rgb(P.highColor),.7));gr.addColorStop(1,css(rgb(P.lowColor),.45));g.fillStyle=gr;g.fill();g.beginPath();for(let x=0;x<=w-15;x++){const y=base-field(x/(w-15),.5,P.seed,P.frequency)*(h-28);x?g.lineTo(7+x,y):g.moveTo(7,y)}g.strokeStyle='rgba(255,255,255,.85)';g.stroke();g.fillStyle='rgba(255,255,255,.3)';g.font='8px ui-sans-serif';g.fillText('W',7,h-3);g.textAlign='right';g.fillText('E',w-8,h-3)}
 const shape=el('div','pcard mp-light te-shape');shape.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Height field</span><span class="s">World extent · procedural frequency</span></div></div>`;const sb=el('div','pbody');shape.append(sb);const size=tape({label:'World size',min:10,max:2000,value:P.size,dec:0,step:10,unit:'m',toPos:v=>Math.log(v/10)/Math.log(200),fromPos:t=>10*Math.pow(200,t),marks:[{t:0,l:'10 m'},{t:.546,l:'180 m'},{t:1,l:'2 km'}],onInput:v=>{setProp(node,'size',Math.round(v));paintAll()}}),relief=tape({label:'Vertical relief',min:0,max:80,value:P.height,dec:1,step:.5,unit:'m',marks:[{t:0,l:'FLAT'},{t:.15,l:'12 m'},{t:1,l:'80 m'}],onInput:v=>{setProp(node,'height',v);paintAll()}}),freq=tape({label:'Feature scale',min:.1,max:8,value:P.frequency,dec:2,step:.05,unit:'×',marks:[{t:0,l:'BROAD'},{t:.139,l:'1.2×'},{t:1,l:'FINE'}],onInput:v=>{setProp(node,'frequency',v);paintAll()}}),seed=tape({label:'Procedural seed',min:0,max:9999,value:P.seed,dec:0,step:1,marks:[{t:0,l:'0'},{t:.0417,l:'417'},{t:1,l:'9999'}],onInput:v=>{setProp(node,'seed',Math.round(v));paintAll()}});sb.append(size,relief,freq,seed);const res=el('div','mp-tags te-res');['64','128','256','512','1024'].forEach(v=>{const b=el('button',`mp-tag${P.resolution===v?' on':''}`,`${v}²`);b.onclick=()=>{setProp(node,'resolution',v);paintAll()};res.append(b)});sb.append(res);host.append(shape);shape.querySelector('.mp-chead .l').onclick=()=>shape.classList.toggle('shut');
 const surface=el('div','pcard mp-light te-surface');surface.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Surface</span><span class="s">Hypsometric colour · shading</span></div></div>`;const ub=el('div','pbody'),colors=el('div','te-colours'),lh=el('div','mp-subhead','<span class="k">valley</span>'),lc=colorChip(P.lowColor,v=>{setProp(node,'lowColor',v);paintAll()}),hh=el('div','mp-subhead','<span class="k">peak</span>'),hc=colorChip(P.highColor,v=>{setProp(node,'highColor',v);paintAll()});lh.append(lc);hh.append(hc);colors.append(lh,hh);ub.append(colors);const rough=tape({label:'Surface roughness',min:0,max:1,value:P.roughness,dec:2,step:.01,marks:[{t:0,l:'MIRROR'},{t:.88,l:'EARTH .88'},{t:1,l:'MATTE'}],onInput:v=>{setProp(node,'roughness',v);paintAll()}});ub.append(rough);const tags=el('div','mp-tags'),wire=pillToggle('WIRE OVERLAY',P.wireframe,v=>{setProp(node,'wireframe',v);paintAll()}),shadow=pillToggle('CAST SHADOW',P.castShadow!==false,v=>{setProp(node,'castShadow',v);paintAll()});tags.append(wire,shadow);ub.append(tags);surface.append(ub);host.append(surface);
 const source=el('div','pcard mp-light te-source');source.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Height source</span><span class="s">Procedural or imported raster</span></div></div>`;const ib=el('div','pbody'),drop=el('div','te-drop',`<b>${P.sourceName||'DROP HEIGHTMAP'}</b><span>PNG · EXR · RAW · 16-BIT TIFF</span>`);ib.append(drop);source.append(ib);host.append(source);['dragover','dragenter'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('file-over')}));drop.ondragleave=()=>drop.classList.remove('file-over');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('file-over');const f=e.dataTransfer.files?.[0];if(!f)return;setProp(node,'sourceName',f.name);setProp(node,'sourceBytes',f.size);paintAll()};
 const transform=el('div','pcard mp-light te-transform');transform.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">World placement</span><span class="s">Terrain datum origin</span></div></div>`;const xb=el('div','pbody'),row=el('div','te-steppers');transform.append(xb);['X','Y','Z'].forEach((k,i)=>{const x=el('div','te-axis',`<span>${k}</span>`),s=stepper({value:pos()[i],min:-9999,max:9999,dec:1,step:.1,unit:i===0?'m':'',onInput:v=>{const a=[...pos()];a[i]=v;setProp(node,'pos',a);paintAll()}});x.append(s);x._step=s;row.append(x)});xb.append(row);host.append(transform);
 function paintAll(){paintHero();paintSection();mArea.innerHTML=`${(P.size*P.size/10000).toFixed(1)}<em>ha</em>`;mRelief.innerHTML=`${P.height.toFixed(1)}<em>m</em>`;mCell.innerHTML=`${(P.size/+P.resolution).toFixed(2)}<em>m</em>`;mSeed.textContent=P.seed;section.querySelector('.mp-num .i').textContent=Math.floor(P.height);section.querySelector('.mp-num .d').textContent='.'+Math.round(P.height*10)%10;section.querySelector('.mp-target .v').textContent=`${(P.height/P.size*100).toFixed(1)}% relief ratio`;[size,relief,freq,seed,rough].forEach((t,i)=>t._set([P.size,P.height,P.frequency,P.seed,P.roughness][i]));[...res.children].forEach((b,i)=>b.classList.toggle('on',['64','128','256','512','1024'][i]===P.resolution));lc._set?.(P.lowColor);hc._set?.(P.highColor);wire._set(P.wireframe);shadow._set(P.castShadow);drop.querySelector('b').textContent=P.sourceName||'DROP HEIGHTMAP';[...row.children].forEach((x,i)=>x._step._set(pos()[i]))}
 register?.(paintAll);const ro=new ResizeObserver(()=>{paintHero();paintSection();[size,relief,freq,seed,rough].forEach(t=>t._paint?.())});ro.observe(host);host._dispose=()=>ro.disconnect();requestAnimationFrame(paintAll);paintAll();return host;
}
