/**
 * Grass parameters and species presets.
 *
 * A grass plant is described botanically: a crown (the tussock base) that
 * bears leaf blades and flowering culms; culms carry a leaf at each node and
 * end in an inflorescence. Lengths are metres, angles degrees.
 */

export type Inflorescence = 'none' | 'spike' | 'foxtail' | 'panicle' | 'plume';

export const INFLORESCENCE_NAMES: Record<Inflorescence, string> = {
  none: 'None (vegetative)',
  spike: 'Spike – wheat, barley',
  foxtail: 'Foxtail – dense bottlebrush',
  panicle: 'Open panicle – oat, meadow grass',
  plume: 'Plume – pampas, reed',
};

/** What the "branches" of the head are, per inflorescence type (UI labels). */
export const HEAD_BRANCH_NAMES: Record<Inflorescence, string> = {
  none: 'Branches',
  spike: 'Spikelets',
  foxtail: 'Bristles',
  panicle: 'Branchlets',
  plume: 'Branchlets',
};

export interface GrassParams {
  // ---- Crown & habit -------------------------------------------------------
  /** Radius of the crown (tussock base) at ground level. */
  crownRadius: number;
  /** Height of the crown dome above the soil (0 = flat pad). */
  crownHeight: number;
  /** How far the crown is sunk into the soil; blades then emerge straight from the ground. */
  crownSink: number;
  /** Dome profile exponent: 2 = rounded, higher = flat top with a rounded shoulder. */
  crownProfile: number;
  /** Radial distribution of the tillers: -1 a ring at the rim, 0 even, 1 crowded at the centre. */
  centreBias: number;

  // ---- Leaf blades from the crown -----------------------------------------
  blades: number;
  bladeLength: number;
  /** ± fraction. */
  bladeLengthV: number;
  bladeWidth: number;
  /** Blade thickness as a fraction of its width. */
  bladeThickness: number;
  /** 0 tapers evenly from the base, 1 keeps its width and ends in a fine point. */
  bladeTaper: number;
  /** Depth of the V-fold along the midrib as a fraction of the width. */
  keel: number;
  /** 0 flat blade, 1 rolled bristle-like blade (fescue, marram). */
  rolled: number;
  /** Twist along the blade, degrees (± twistV). */
  twist: number;
  twistV: number;
  /** Tilt from the vertical at the rim of the crown (the centre stays upright), degrees. */
  lean: number;
  leanV: number;
  /** Arch from base to tip, degrees. */
  droop: number;
  droopV: number;
  /** 1 bends evenly, higher keeps the base stiff and lets the tip hang. */
  droopPower: number;
  /** Lateral waviness, degrees. */
  wave: number;

  // ---- Culms (flowering stems) ---------------------------------------------
  culms: number;
  culmHeight: number;
  culmHeightV: number;
  culmRadius: number;
  culmLean: number;
  culmLeanV: number;
  /** Bend along the culm, degrees. */
  culmCurve: number;
  /** Leaf nodes per culm. */
  nodes: number;
  /** Relative swelling of the culm at the nodes. */
  nodeSwell: number;
  /** Culm leaf length relative to the basal blades. */
  culmLeafLength: number;
  /** Culm leaf width relative to the basal blades. */
  culmLeafWidth: number;
  /** Angle between a culm leaf and the culm, degrees. */
  culmLeafAngle: number;

  // ---- Inflorescence -------------------------------------------------------
  head: Inflorescence;
  headLength: number;
  /** Thickness of a spike or foxtail; panicles and plumes spread by their branchlet angle instead. */
  headWidth: number;
  /** Nod of the head, degrees. */
  headDroop: number;
  /** Spikelets (spike), bristles (foxtail) or branchlets (panicle, plume). */
  headBranches: number;
  /** Branchlet length relative to the head length (panicle, plume). */
  headBranchLength: number;
  /** Angle between a branchlet and the rachis, degrees. */
  headBranchAngle: number;
  /** Arch of a branchlet, degrees. */
  headBranchDroop: number;
  /** Fraction of the head length (from its base) over which branchlets attach. */
  headBranchSpread: number;
  /** Branchlet radius. */
  headBranchRadius: number;
  /** Secondary branchlets per branchlet (panicle, plume). */
  headSecondary: number;
  /** Spikelet radius: the body of a spike's spikelets, the bulge at the tip of a panicle branchlet (0 = none). */
  spikelet: number;
  /** Awn length (0 = none): from each spikelet of a spike, beyond the spikelet of a panicle branchlet. */
  awn: number;

  // ---- Mesh resolution -----------------------------------------------------
  /** Rings along a blade. */
  bladeSegments: number;
  /** Vertices around a blade: 4 flat strip, 6 keeled, 8 keeled and wide. */
  bladeSides: number;
  /** Vertices around a culm (6, 8, 10 or 12). */
  culmSides: number;
  /** Rings along a culm (below the head). */
  culmSegments: number;
  /** Rings along a branchlet or bristle. */
  branchletSegments: number;
  /** Intermediate loops between a window and the first ring of the tiller. */
  collarRings: number;
}

export const DEFAULT_GRASS: GrassParams = {
  crownRadius: 0.12,
  crownHeight: 0.03,
  crownSink: 0.01,
  crownProfile: 2.5,
  centreBias: 0,

  blades: 180,
  bladeLength: 0.32,
  bladeLengthV: 0.3,
  bladeWidth: 0.004,
  bladeThickness: 0.12,
  bladeTaper: 0.6,
  keel: 0.4,
  rolled: 0,
  twist: 60,
  twistV: 60,
  lean: 32,
  leanV: 12,
  droop: 70,
  droopV: 30,
  droopPower: 1.8,
  wave: 6,

  culms: 14,
  culmHeight: 0.6,
  culmHeightV: 0.15,
  culmRadius: 0.0015,
  culmLean: 8,
  culmLeanV: 6,
  culmCurve: 6,
  nodes: 2,
  nodeSwell: 0.15,
  culmLeafLength: 0.55,
  culmLeafWidth: 1,
  culmLeafAngle: 35,

  head: 'panicle',
  headLength: 0.12,
  headWidth: 0.07,
  headDroop: 10,
  headBranches: 24,
  headBranchLength: 0.4,
  headBranchAngle: 40,
  headBranchDroop: 15,
  headBranchSpread: 0.85,
  headBranchRadius: 0.0005,
  headSecondary: 0,
  spikelet: 0.002,
  awn: 0,

  bladeSegments: 8,
  bladeSides: 6,
  culmSides: 6,
  culmSegments: 14,
  branchletSegments: 3,
  collarRings: 1,
};

/** Approximate height of a grass plant (m), for the library metadata and framing. */
export function grassHeight(g: GrassParams): number {
  const bladeTop = Math.max(0, g.crownHeight - g.crownSink) + g.bladeLength * 0.85;
  const culmTop = g.culms > 0 ? g.culmHeight * (1 + g.culmHeightV * 0.5) + (g.head === 'none' ? 0 : g.headLength) : 0;
  return Math.max(0.03, bladeTop, culmTop);
}

/** Habit word used in the species metadata. */
export function grassHabit(g: GrassParams): string {
  if (g.crownSink >= g.crownHeight && g.crownRadius > 0.08 && g.culms < 8) return 'turf';
  if (g.crownRadius < 0.05) return 'single culms';
  if (g.crownRadius >= 0.25) return 'large tussock';
  return 'tussock';
}

/** Species presets. Values are typical field measurements of the species. */
export const GRASS_PRESETS: { name: string; grass: Partial<GrassParams> }[] = [
  // ---- turf & meadow --------------------------------------------------------
  {
    name: 'Lawn Turf',
    grass: {
      crownRadius: 0.14,
      crownHeight: 0.012,
      crownSink: 0.01,
      crownProfile: 3,
      blades: 330,
      bladeLength: 0.09,
      bladeLengthV: 0.3,
      bladeWidth: 0.0035,
      bladeThickness: 0.12,
      bladeTaper: 0.6,
      keel: 0.35,
      twist: 40,
      twistV: 60,
      lean: 28,
      leanV: 12,
      droop: 30,
      droopV: 20,
      droopPower: 1.6,
      wave: 4,
      culms: 0,
      head: 'none',
      bladeSegments: 6,
      bladeSides: 4,
    },
  },
  {
    name: 'Meadow Grass',
    grass: { headBranches: 28, headSecondary: 2 }, // otherwise the defaults: Poa pratensis
  },
  {
    name: 'Timothy',
    grass: {
      crownRadius: 0.1,
      crownHeight: 0.03,
      crownSink: 0.01,
      blades: 120,
      bladeLength: 0.3,
      bladeLengthV: 0.3,
      bladeWidth: 0.007,
      keel: 0.3,
      twist: 50,
      twistV: 50,
      lean: 30,
      droop: 60,
      droopV: 25,
      culms: 16,
      culmHeight: 0.9,
      culmHeightV: 0.12,
      culmRadius: 0.002,
      culmLean: 6,
      culmLeanV: 5,
      culmCurve: 5,
      nodes: 3,
      nodeSwell: 0.2,
      culmLeafLength: 0.6,
      culmLeafAngle: 30,
      head: 'foxtail',
      headLength: 0.09,
      headWidth: 0.009,
      headDroop: 4,
      headBranches: 140,
      headBranchAngle: 60,
      headBranchDroop: 10,
      headBranchSpread: 1,
      headBranchRadius: 0.0004,
      culmSides: 8,
      branchletSegments: 2,
    },
  },
  {
    name: 'Red Oat Grass',
    grass: {
      crownRadius: 0.12,
      crownHeight: 0.05,
      crownSink: 0,
      blades: 160,
      bladeLength: 0.35,
      bladeLengthV: 0.35,
      bladeWidth: 0.004,
      keel: 0.3,
      rolled: 0.3,
      twist: 90,
      twistV: 90,
      lean: 30,
      leanV: 12,
      droop: 55,
      droopV: 30,
      droopPower: 1.7,
      culms: 22,
      culmHeight: 0.9,
      culmHeightV: 0.2,
      culmRadius: 0.0018,
      culmLean: 10,
      culmLeanV: 6,
      culmCurve: 12,
      nodes: 3,
      nodeSwell: 0.18,
      culmLeafLength: 0.5,
      culmLeafAngle: 30,
      head: 'panicle',
      headLength: 0.28,
      headWidth: 0.12,
      headDroop: 25,
      headBranches: 12,
      headBranchLength: 0.35,
      headBranchAngle: 35,
      headBranchDroop: 70,
      headBranchSpread: 0.9,
      headBranchRadius: 0.0006,
      headSecondary: 2,
      spikelet: 0.003,
      awn: 0.05,
      culmSides: 6,
      branchletSegments: 4,
    },
  },

  // ---- tussocks -------------------------------------------------------------
  {
    name: 'Blue Fescue',
    grass: {
      crownRadius: 0.11,
      crownHeight: 0.025,
      crownSink: 0.01,
      crownProfile: 2,
      centreBias: -0.2,
      blades: 900,
      bladeLength: 0.22,
      bladeLengthV: 0.25,
      bladeWidth: 0.0022,
      bladeThickness: 0.5,
      bladeTaper: 0.5,
      keel: 0,
      rolled: 0.85,
      twist: 0,
      twistV: 0,
      lean: 50,
      leanV: 15,
      droop: 55,
      droopV: 30,
      droopPower: 1.5,
      wave: 5,
      culms: 18,
      culmHeight: 0.42,
      culmHeightV: 0.1,
      culmRadius: 0.001,
      culmLean: 12,
      culmLeanV: 8,
      culmCurve: 10,
      nodes: 1,
      nodeSwell: 0.1,
      culmLeafLength: 0.4,
      culmLeafAngle: 25,
      head: 'panicle',
      headLength: 0.08,
      headWidth: 0.02,
      headDroop: 8,
      headBranches: 10,
      headBranchLength: 0.3,
      headBranchAngle: 20,
      headBranchDroop: 10,
      headBranchSpread: 0.8,
      headBranchRadius: 0.0004,
      spikelet: 0.0018,
      awn: 0.004,
      bladeSegments: 7,
      bladeSides: 4,
      culmSides: 6,
    },
  },
  {
    name: 'Fountain Grass',
    grass: {
      crownRadius: 0.16,
      crownHeight: 0.07,
      crownSink: 0,
      blades: 300,
      bladeLength: 0.55,
      bladeLengthV: 0.25,
      bladeWidth: 0.004,
      keel: 0.35,
      rolled: 0.3,
      twist: 120,
      twistV: 90,
      lean: 40,
      leanV: 12,
      droop: 110,
      droopV: 30,
      droopPower: 1.6,
      wave: 6,
      culms: 30,
      culmHeight: 0.8,
      culmHeightV: 0.15,
      culmRadius: 0.0016,
      culmLean: 22,
      culmLeanV: 8,
      culmCurve: 35,
      nodes: 2,
      nodeSwell: 0.12,
      culmLeafLength: 0.5,
      culmLeafAngle: 30,
      head: 'foxtail',
      headLength: 0.22,
      headWidth: 0.04,
      headDroop: 45,
      headBranches: 220,
      headBranchAngle: 50,
      headBranchDroop: 25,
      headBranchSpread: 1,
      headBranchRadius: 0.0006,
      bladeSegments: 10,
      culmSides: 8,
      branchletSegments: 3,
    },
  },
  {
    name: 'Marram Grass',
    grass: {
      crownRadius: 0.14,
      crownHeight: 0.04,
      crownSink: 0.02,
      blades: 200,
      bladeLength: 0.7,
      bladeLengthV: 0.25,
      bladeWidth: 0.004,
      bladeThickness: 0.35,
      bladeTaper: 0.5,
      keel: 0.1,
      rolled: 0.8,
      twist: 0,
      twistV: 20,
      lean: 18,
      leanV: 10,
      droop: 25,
      droopV: 15,
      droopPower: 2,
      wave: 4,
      culms: 12,
      culmHeight: 1.0,
      culmHeightV: 0.15,
      culmRadius: 0.0025,
      culmLean: 5,
      culmLeanV: 4,
      culmCurve: 4,
      nodes: 2,
      nodeSwell: 0.12,
      culmLeafLength: 0.6,
      culmLeafAngle: 20,
      head: 'foxtail',
      headLength: 0.2,
      headWidth: 0.014,
      headDroop: 3,
      headBranches: 90,
      headBranchAngle: 30,
      headBranchDroop: 5,
      headBranchSpread: 1,
      headBranchRadius: 0.0005,
      bladeSegments: 9,
      bladeSides: 4,
      culmSides: 8,
      branchletSegments: 2,
    },
  },
  {
    name: 'Chinese Silver Grass',
    grass: {
      crownRadius: 0.3,
      crownHeight: 0.15,
      crownSink: 0,
      blades: 360,
      bladeLength: 1.0,
      bladeLengthV: 0.25,
      bladeWidth: 0.012,
      bladeThickness: 0.08,
      bladeTaper: 0.75,
      keel: 0.3,
      twist: 90,
      twistV: 90,
      lean: 25,
      leanV: 12,
      droop: 90,
      droopV: 35,
      droopPower: 2,
      wave: 5,
      culms: 40,
      culmHeight: 1.9,
      culmHeightV: 0.2,
      culmRadius: 0.004,
      culmLean: 8,
      culmLeanV: 5,
      culmCurve: 8,
      nodes: 4,
      nodeSwell: 0.12,
      culmLeafLength: 0.5,
      culmLeafAngle: 40,
      head: 'plume',
      headLength: 0.25,
      headWidth: 0.12,
      headDroop: 20,
      headBranches: 24,
      headBranchLength: 0.9,
      headBranchAngle: 22,
      headBranchDroop: 35,
      headBranchSpread: 0.25,
      headBranchRadius: 0.0008,
      headSecondary: 4,
      bladeSegments: 14,
      bladeSides: 6,
      culmSides: 8,
      culmSegments: 20,
      branchletSegments: 4,
    },
  },
  {
    name: 'Pampas Grass',
    grass: {
      crownRadius: 0.45,
      crownHeight: 0.25,
      crownSink: 0,
      crownProfile: 2.5,
      blades: 520,
      bladeLength: 1.5,
      bladeLengthV: 0.3,
      bladeWidth: 0.012,
      bladeThickness: 0.06,
      bladeTaper: 0.85,
      keel: 0.35,
      twist: 150,
      twistV: 90,
      lean: 35,
      leanV: 15,
      droop: 140,
      droopV: 30,
      droopPower: 1.7,
      wave: 6,
      culms: 24,
      culmHeight: 2.4,
      culmHeightV: 0.12,
      culmRadius: 0.007,
      culmLean: 6,
      culmLeanV: 4,
      culmCurve: 4,
      nodes: 3,
      nodeSwell: 0.1,
      culmLeafLength: 0.35,
      culmLeafAngle: 30,
      head: 'plume',
      headLength: 0.5,
      headWidth: 0.14,
      headDroop: 10,
      headBranches: 100,
      headBranchLength: 0.22,
      headBranchAngle: 25,
      headBranchDroop: 20,
      headBranchSpread: 1,
      headBranchRadius: 0.001,
      headSecondary: 2,
      bladeSegments: 16,
      bladeSides: 6,
      culmSides: 8,
      culmSegments: 24,
      branchletSegments: 3,
    },
  },

  // ---- cereals & reeds ------------------------------------------------------
  {
    name: 'Wheat',
    grass: {
      crownRadius: 0.035,
      crownHeight: 0.01,
      crownSink: 0.01,
      blades: 6,
      bladeLength: 0.25,
      bladeLengthV: 0.2,
      bladeWidth: 0.012,
      bladeThickness: 0.06,
      bladeTaper: 0.7,
      keel: 0.25,
      twist: 40,
      twistV: 40,
      lean: 30,
      leanV: 10,
      droop: 60,
      droopV: 20,
      culms: 5,
      culmHeight: 0.85,
      culmHeightV: 0.06,
      culmRadius: 0.002,
      culmLean: 4,
      culmLeanV: 3,
      culmCurve: 5,
      nodes: 4,
      nodeSwell: 0.25,
      culmLeafLength: 0.8,
      culmLeafWidth: 1.1,
      culmLeafAngle: 40,
      head: 'spike',
      headLength: 0.09,
      headWidth: 0.012,
      headDroop: 15,
      headBranches: 18,
      headBranchAngle: 22,
      headBranchDroop: 5,
      headBranchRadius: 0.0004,
      spikelet: 0.0028,
      awn: 0.03,
      bladeSegments: 8,
      culmSides: 8,
      culmSegments: 16,
      branchletSegments: 3,
    },
  },
  {
    name: 'Barley',
    grass: {
      crownRadius: 0.035,
      crownHeight: 0.01,
      crownSink: 0.01,
      blades: 6,
      bladeLength: 0.24,
      bladeLengthV: 0.2,
      bladeWidth: 0.014,
      bladeThickness: 0.06,
      bladeTaper: 0.7,
      keel: 0.25,
      twist: 40,
      twistV: 40,
      lean: 32,
      leanV: 10,
      droop: 65,
      droopV: 20,
      culms: 5,
      culmHeight: 0.8,
      culmHeightV: 0.06,
      culmRadius: 0.002,
      culmLean: 4,
      culmLeanV: 3,
      culmCurve: 5,
      nodes: 4,
      nodeSwell: 0.25,
      culmLeafLength: 0.75,
      culmLeafWidth: 1.1,
      culmLeafAngle: 42,
      head: 'spike',
      headLength: 0.08,
      headWidth: 0.011,
      headDroop: 70,
      headBranches: 22,
      headBranchAngle: 20,
      headBranchDroop: 4,
      headBranchRadius: 0.00035,
      spikelet: 0.0022,
      awn: 0.14,
      bladeSegments: 8,
      culmSides: 8,
      culmSegments: 16,
      branchletSegments: 4,
    },
  },
  {
    name: 'Oat',
    grass: {
      crownRadius: 0.035,
      crownHeight: 0.01,
      crownSink: 0.01,
      blades: 6,
      bladeLength: 0.28,
      bladeLengthV: 0.2,
      bladeWidth: 0.012,
      bladeThickness: 0.06,
      bladeTaper: 0.7,
      keel: 0.25,
      twist: 40,
      twistV: 40,
      lean: 30,
      leanV: 10,
      droop: 60,
      droopV: 20,
      culms: 5,
      culmHeight: 1.1,
      culmHeightV: 0.08,
      culmRadius: 0.0022,
      culmLean: 5,
      culmLeanV: 3,
      culmCurve: 8,
      nodes: 4,
      nodeSwell: 0.22,
      culmLeafLength: 0.8,
      culmLeafWidth: 1.1,
      culmLeafAngle: 40,
      head: 'panicle',
      headLength: 0.25,
      headWidth: 0.18,
      headDroop: 12,
      headBranches: 26,
      headBranchLength: 0.45,
      headBranchAngle: 45,
      headBranchDroop: 60,
      headBranchSpread: 0.85,
      headBranchRadius: 0.0005,
      headSecondary: 2,
      spikelet: 0.004,
      awn: 0.02,
      bladeSegments: 8,
      culmSides: 8,
      culmSegments: 16,
      branchletSegments: 4,
    },
  },
  {
    name: 'Common Reed',
    grass: {
      crownRadius: 0.06,
      crownHeight: 0.02,
      crownSink: 0.02,
      blades: 4,
      bladeLength: 0.45,
      bladeLengthV: 0.2,
      bladeWidth: 0.025,
      bladeThickness: 0.05,
      bladeTaper: 0.7,
      keel: 0.2,
      twist: 30,
      twistV: 40,
      lean: 30,
      leanV: 10,
      droop: 50,
      droopV: 20,
      droopPower: 1.6,
      culms: 3,
      culmHeight: 3.0,
      culmHeightV: 0.1,
      culmRadius: 0.007,
      culmLean: 3,
      culmLeanV: 2,
      culmCurve: 6,
      nodes: 9,
      nodeSwell: 0.12,
      culmLeafLength: 1.0,
      culmLeafWidth: 1,
      culmLeafAngle: 45,
      head: 'plume',
      headLength: 0.32,
      headWidth: 0.15,
      headDroop: 30,
      headBranches: 90,
      headBranchLength: 0.4,
      headBranchAngle: 30,
      headBranchDroop: 30,
      headBranchSpread: 0.9,
      headBranchRadius: 0.0007,
      headSecondary: 4,
      bladeSegments: 10,
      bladeSides: 8,
      culmSides: 8,
      culmSegments: 30,
      branchletSegments: 4,
    },
  },
  {
    name: 'Elephant Grass',
    grass: {
      crownRadius: 0.35,
      crownHeight: 0.12,
      crownSink: 0,
      blades: 60,
      bladeLength: 0.9,
      bladeLengthV: 0.25,
      bladeWidth: 0.03,
      bladeThickness: 0.05,
      bladeTaper: 0.7,
      keel: 0.25,
      twist: 60,
      twistV: 60,
      lean: 35,
      leanV: 12,
      droop: 80,
      droopV: 30,
      droopPower: 1.8,
      culms: 26,
      culmHeight: 3.0,
      culmHeightV: 0.15,
      culmRadius: 0.012,
      culmLean: 8,
      culmLeanV: 5,
      culmCurve: 10,
      nodes: 8,
      nodeSwell: 0.15,
      culmLeafLength: 0.9,
      culmLeafWidth: 1,
      culmLeafAngle: 50,
      head: 'foxtail',
      headLength: 0.22,
      headWidth: 0.035,
      headDroop: 10,
      headBranches: 200,
      headBranchAngle: 45,
      headBranchDroop: 15,
      headBranchSpread: 1,
      headBranchRadius: 0.0008,
      bladeSegments: 12,
      bladeSides: 8,
      culmSides: 8,
      culmSegments: 30,
      branchletSegments: 3,
    },
  },

  // ───────────────────────────────────── desert succulent rosettes ──────────
  // Agave / Aloe / Sotol are not grasses botanically, but they share the
  // welded grass topology: a crown dome with thick succulent blades welded
  // through windows. That gives them the same AAA single-manifold guarantee
  // and wind as the wild grasses, but with the massive fleshy sections GTA 6 needs.
  {
    name: 'Century Agave',
    grass: {
      crownRadius: 0.18,
      crownHeight: 0.05,
      crownSink: 0.01,
      crownProfile: 2.2,
      centreBias: 0.1,
      blades: 44,
      bladeLength: 0.72,
      bladeLengthV: 0.22,
      bladeWidth: 0.12,
      bladeThickness: 0.26,
      bladeTaper: 0.72,
      keel: 0.32,
      rolled: 0,
      twist: 18,
      twistV: 18,
      lean: 68,
      leanV: 14,
      droop: 18,
      droopV: 12,
      droopPower: 1.4,
      wave: 3,
      culms: 0,
      head: 'none',
      bladeSegments: 12,
      bladeSides: 8,
      culmSides: 8,
      culmSegments: 14,
      branchletSegments: 2,
      collarRings: 1,
    },
  },
  {
    name: "Parry's Agave",
    grass: {
      crownRadius: 0.14,
      crownHeight: 0.04,
      crownSink: 0.005,
      crownProfile: 2.4,
      centreBias: 0.15,
      blades: 52,
      bladeLength: 0.38,
      bladeLengthV: 0.18,
      bladeWidth: 0.095,
      bladeThickness: 0.32,
      bladeTaper: 0.58,
      keel: 0.28,
      rolled: 0,
      twist: 14,
      twistV: 14,
      lean: 72,
      leanV: 12,
      droop: 22,
      droopV: 10,
      droopPower: 1.35,
      wave: 2,
      culms: 0,
      head: 'none',
      bladeSegments: 10,
      bladeSides: 8,
      culmSides: 6,
      branchletSegments: 2,
      collarRings: 1,
    },
  },
  {
    name: 'Aloe Vera',
    grass: {
      crownRadius: 0.11,
      crownHeight: 0.025,
      crownSink: 0.005,
      crownProfile: 2.0,
      centreBias: 0.05,
      blades: 28,
      bladeLength: 0.32,
      bladeLengthV: 0.2,
      bladeWidth: 0.065,
      bladeThickness: 0.34,
      bladeTaper: 0.64,
      keel: 0.22,
      rolled: 0,
      twist: 22,
      twistV: 22,
      lean: 62,
      leanV: 16,
      droop: 28,
      droopV: 14,
      droopPower: 1.5,
      wave: 4,
      culms: 1,
      culmHeight: 0.55,
      culmHeightV: 0.1,
      culmRadius: 0.0045,
      culmLean: 4,
      culmLeanV: 3,
      culmCurve: 4,
      nodes: 0,
      nodeSwell: 0,
      culmLeafLength: 0.5,
      culmLeafWidth: 0.6,
      culmLeafAngle: 30,
      head: 'panicle',
      headLength: 0.14,
      headWidth: 0.04,
      headDroop: 6,
      headBranches: 18,
      headBranchLength: 0.3,
      headBranchAngle: 35,
      headBranchDroop: 10,
      headBranchSpread: 0.7,
      headBranchRadius: 0.0006,
      headSecondary: 1,
      spikelet: 0.003,
      awn: 0,
      bladeSegments: 10,
      bladeSides: 8,
      culmSides: 8,
      culmSegments: 10,
      branchletSegments: 3,
    },
  },
  {
    name: 'Desert Spoon',
    grass: {
      // Dasylirion wheeleri – sotol: a dense spherical rosette of 200+ long,
      // narrow, saw-toothed leaves with a tall flowering stalk.
      crownRadius: 0.22,
      crownHeight: 0.06,
      crownSink: 0,
      crownProfile: 2.6,
      centreBias: -0.05,
      blades: 220,
      bladeLength: 0.85,
      bladeLengthV: 0.18,
      bladeWidth: 0.018,
      bladeThickness: 0.18,
      bladeTaper: 0.78,
      keel: 0.32,
      rolled: 0.15,
      twist: 8,
      twistV: 20,
      lean: 58,
      leanV: 18,
      droop: 42,
      droopV: 22,
      droopPower: 1.6,
      wave: 5,
      culms: 1,
      culmHeight: 2.2,
      culmHeightV: 0.12,
      culmRadius: 0.007,
      culmLean: 2,
      culmLeanV: 2,
      culmCurve: 3,
      nodes: 0,
      culmLeafLength: 0.5,
      culmLeafWidth: 0.7,
      culmLeafAngle: 28,
      head: 'plume',
      headLength: 0.45,
      headWidth: 0.12,
      headDroop: 4,
      headBranches: 60,
      headBranchLength: 0.25,
      headBranchAngle: 30,
      headBranchDroop: 10,
      headBranchSpread: 1,
      headBranchRadius: 0.0007,
      headSecondary: 2,
      bladeSegments: 12,
      bladeSides: 6,
      culmSides: 8,
      culmSegments: 18,
      branchletSegments: 3,
    },
  },
  {
    name: 'Echeveria',
    grass: {
      // Echeveria elegans – Mexican snowball: a tight 14 cm waxy rosette,
      // powder-blue, 60-80 short fat leaves in a perfect spiral.
      crownRadius: 0.07,
      crownHeight: 0.015,
      crownSink: 0.005,
      crownProfile: 2.0,
      centreBias: 0.25,
      blades: 72,
      bladeLength: 0.075,
      bladeLengthV: 0.12,
      bladeWidth: 0.045,
      bladeThickness: 0.44,
      bladeTaper: 0.38,
      keel: 0.08,
      rolled: 0,
      twist: 6,
      twistV: 10,
      lean: 82,
      leanV: 8,
      droop: 12,
      droopV: 8,
      droopPower: 1.3,
      wave: 2,
      culms: 1,
      culmHeight: 0.22,
      culmHeightV: 0.08,
      culmRadius: 0.003,
      culmLean: 6,
      culmLeanV: 4,
      culmCurve: 8,
      nodes: 0,
      culmLeafLength: 0.4,
      culmLeafWidth: 0.5,
      culmLeafAngle: 35,
      head: 'panicle',
      headLength: 0.08,
      headWidth: 0.03,
      headDroop: 12,
      headBranches: 10,
      headBranchLength: 0.4,
      headBranchAngle: 28,
      headBranchDroop: 15,
      headBranchSpread: 0.6,
      headBranchRadius: 0.00045,
      headSecondary: 0,
      spikelet: 0.002,
      awn: 0,
      bladeSegments: 8,
      bladeSides: 8,
      culmSides: 6,
      culmSegments: 8,
      branchletSegments: 2,
      collarRings: 1,
    },
  },
  {
    name: 'Haworthia',
    grass: {
      // Haworthia fasciata – zebra plant: dark 10 cm rosette, white-banded
      // triangular leaves, short and very thick.
      crownRadius: 0.055,
      crownHeight: 0.018,
      crownSink: 0.005,
      crownProfile: 2.4,
      centreBias: 0.1,
      blades: 34,
      bladeLength: 0.065,
      bladeLengthV: 0.15,
      bladeWidth: 0.028,
      bladeThickness: 0.48,
      bladeTaper: 0.42,
      keel: 0.42,
      rolled: 0,
      twist: 10,
      twistV: 10,
      lean: 76,
      leanV: 10,
      droop: 8,
      droopV: 6,
      droopPower: 1.2,
      wave: 1,
      culms: 1,
      culmHeight: 0.28,
      culmHeightV: 0.1,
      culmRadius: 0.0025,
      culmLean: 4,
      culmLeanV: 3,
      culmCurve: 5,
      nodes: 0,
      head: 'panicle',
      headLength: 0.06,
      headWidth: 0.02,
      headDroop: 5,
      headBranches: 8,
      headBranchLength: 0.35,
      headBranchAngle: 30,
      headBranchDroop: 8,
      headBranchSpread: 0.7,
      headBranchRadius: 0.0004,
      spikelet: 0.0015,
      bladeSegments: 8,
      bladeSides: 8,
      culmSides: 6,
      culmSegments: 8,
      branchletSegments: 2,
    },
  },
  {
    name: 'Jade Plant',
    grass: {
      // Crassula ovata – jade: shrubby 40 cm succulent with woody brown stems
      // and glossy oval leaves; not a grass but welded as a crown+blades+capped culms.
      crownRadius: 0.14,
      crownHeight: 0.04,
      crownSink: 0,
      crownProfile: 2.8,
      centreBias: 0,
      blades: 86,
      bladeLength: 0.045,
      bladeLengthV: 0.14,
      bladeWidth: 0.028,
      bladeThickness: 0.52,
      bladeTaper: 0.28,
      keel: 0.05,
      rolled: 0,
      twist: 4,
      twistV: 8,
      lean: 64,
      leanV: 18,
      droop: 14,
      droopV: 10,
      droopPower: 1.4,
      wave: 2,
      culms: 6,
      culmHeight: 0.42,
      culmHeightV: 0.12,
      culmRadius: 0.006,
      culmLean: 18,
      culmLeanV: 10,
      culmCurve: 12,
      nodes: 3,
      nodeSwell: 0.08,
      culmLeafLength: 0.9,
      culmLeafWidth: 0.9,
      culmLeafAngle: 55,
      head: 'panicle',
      headLength: 0.07,
      headWidth: 0.04,
      headDroop: 8,
      headBranches: 14,
      headBranchLength: 0.4,
      headBranchAngle: 32,
      headBranchDroop: 12,
      headBranchSpread: 0.6,
      headBranchRadius: 0.0005,
      headSecondary: 1,
      spikelet: 0.0012,
      bladeSegments: 7,
      bladeSides: 8,
      culmSides: 8,
      culmSegments: 10,
      branchletSegments: 2,
      collarRings: 1,
    },
  },

  // ──────────────────────────────────────── desert rosettes · second pass ───
  // These additions deliberately stay within the welded blade/crown pipeline:
  // thick keeled leaves, measured crown proportions, and no billboard-only
  // shortcuts. They are small enough to inspect at close range but still
  // useful as scatter assets in a GTA-scale desert.
  {
    name: 'Blue Agave',
    grass: {
      // Agave tequilana – broad blue-grey leaves in a rigid, open rosette.
      crownRadius: 0.2,
      crownHeight: 0.055,
      crownSink: 0.008,
      crownProfile: 2.4,
      centreBias: 0.18,
      blades: 58,
      bladeLength: 0.88,
      bladeLengthV: 0.18,
      bladeWidth: 0.14,
      bladeThickness: 0.3,
      bladeTaper: 0.72,
      keel: 0.38,
      rolled: 0,
      twist: 16,
      twistV: 14,
      lean: 70,
      leanV: 12,
      droop: 24,
      droopV: 12,
      droopPower: 1.5,
      wave: 2,
      culms: 0,
      head: 'none',
      bladeSegments: 14,
      bladeSides: 8,
      culmSides: 8,
      culmSegments: 12,
      branchletSegments: 2,
      collarRings: 1,
    },
  },
  {
    name: 'Red Yucca',
    grass: {
      // Hesperaloe parviflora – narrow arching leaves and a tall pink-flowered
      // scape. The plume head keeps its characteristic airy silhouette.
      crownRadius: 0.16,
      crownHeight: 0.045,
      crownSink: 0.004,
      crownProfile: 2.5,
      centreBias: 0.05,
      blades: 132,
      bladeLength: 0.62,
      bladeLengthV: 0.2,
      bladeWidth: 0.012,
      bladeThickness: 0.2,
      bladeTaper: 0.78,
      keel: 0.28,
      rolled: 0.1,
      twist: 10,
      twistV: 16,
      lean: 64,
      leanV: 16,
      droop: 48,
      droopV: 22,
      droopPower: 1.7,
      wave: 4,
      culms: 3,
      culmHeight: 1.25,
      culmHeightV: 0.12,
      culmRadius: 0.0032,
      culmLean: 5,
      culmLeanV: 4,
      culmCurve: 5,
      nodes: 0,
      culmLeafLength: 0.48,
      culmLeafWidth: 0.8,
      culmLeafAngle: 28,
      head: 'plume',
      headLength: 0.24,
      headWidth: 0.1,
      headDroop: 7,
      headBranches: 28,
      headBranchLength: 0.42,
      headBranchAngle: 26,
      headBranchDroop: 16,
      headBranchSpread: 0.9,
      headBranchRadius: 0.00045,
      headSecondary: 1,
      spikelet: 0.0025,
      awn: 0,
      bladeSegments: 11,
      bladeSides: 6,
      culmSides: 8,
      culmSegments: 18,
      branchletSegments: 3,
      collarRings: 1,
    },
  },
  {
    name: 'Beargrass',
    grass: {
      // Nolina microcarpa – fine, stiff, fountain-like leaves; unlike sotol it
      // has no towering bloom stalk in the asset's vegetative state.
      crownRadius: 0.19,
      crownHeight: 0.045,
      crownSink: 0.004,
      crownProfile: 2.3,
      centreBias: -0.12,
      blades: 300,
      bladeLength: 0.72,
      bladeLengthV: 0.2,
      bladeWidth: 0.007,
      bladeThickness: 0.26,
      bladeTaper: 0.74,
      keel: 0.24,
      rolled: 0.35,
      twist: 8,
      twistV: 18,
      lean: 54,
      leanV: 18,
      droop: 62,
      droopV: 24,
      droopPower: 1.7,
      wave: 5,
      culms: 0,
      head: 'none',
      bladeSegments: 12,
      bladeSides: 6,
      culmSides: 6,
      culmSegments: 12,
      branchletSegments: 2,
      collarRings: 1,
    },
  },
  {
    name: 'Dudleya Rosette',
    grass: {
      // Dudleya brittonii – chalk dudleya, a powdery blue-green succulent with
      // a low solitary rosette and pointed, fleshy leaves.
      crownRadius: 0.085,
      crownHeight: 0.018,
      crownSink: 0.004,
      crownProfile: 2.1,
      centreBias: 0.28,
      blades: 48,
      bladeLength: 0.12,
      bladeLengthV: 0.15,
      bladeWidth: 0.052,
      bladeThickness: 0.46,
      bladeTaper: 0.42,
      keel: 0.12,
      rolled: 0,
      twist: 7,
      twistV: 10,
      lean: 80,
      leanV: 8,
      droop: 14,
      droopV: 8,
      droopPower: 1.25,
      wave: 1,
      culms: 0,
      head: 'none',
      bladeSegments: 9,
      bladeSides: 8,
      culmSides: 6,
      culmSegments: 8,
      branchletSegments: 2,
      collarRings: 1,
    },
  },
  {
    name: 'Living Stones',
    grass: {
      // Lithops lesliei – paired, low succulent bodies. A compact crown and
      // short, broad, heavily keeled leaves create the two-lobed pebble rhythm
      // without inventing foliage that the species does not have.
      crownRadius: 0.075,
      crownHeight: 0.028,
      crownSink: 0.012,
      crownProfile: 3.4,
      centreBias: 0.35,
      blades: 16,
      bladeLength: 0.048,
      bladeLengthV: 0.08,
      bladeWidth: 0.052,
      bladeThickness: 0.68,
      bladeTaper: 0.18,
      keel: 0.65,
      rolled: 0,
      twist: 3,
      twistV: 5,
      lean: 88,
      leanV: 4,
      droop: 4,
      droopV: 3,
      droopPower: 1,
      wave: 0,
      culms: 0,
      head: 'none',
      bladeSegments: 7,
      bladeSides: 8,
      culmSides: 6,
      culmSegments: 6,
      branchletSegments: 2,
      collarRings: 1,
    },
  },
  {
    name: 'Snake Plant',
    grass: {
      // Dracaena trifasciata – upright sword-like succulent leaves, a useful
      // shaded patio / dry-wash accent rather than a generic grass clump.
      crownRadius: 0.13,
      crownHeight: 0.035,
      crownSink: 0.004,
      crownProfile: 2.8,
      centreBias: 0.18,
      blades: 28,
      bladeLength: 0.72,
      bladeLengthV: 0.14,
      bladeWidth: 0.075,
      bladeThickness: 0.4,
      bladeTaper: 0.55,
      keel: 0.48,
      rolled: 0,
      twist: 5,
      twistV: 8,
      lean: 12,
      leanV: 8,
      droop: 8,
      droopV: 6,
      droopPower: 1.2,
      wave: 1,
      culms: 0,
      head: 'none',
      bladeSegments: 12,
      bladeSides: 8,
      culmSides: 8,
      culmSegments: 10,
      branchletSegments: 2,
      collarRings: 1,
    },
  },

  {
    name: 'Queen Victoria Agave',
    grass: {
      // Agave victoriae-reginae – compact geometric rosette with short,
      // broad, rigid leaves and a dark terminal spine.
      crownRadius: 0.14,
      crownHeight: 0.045,
      crownSink: 0.006,
      crownProfile: 2.6,
      centreBias: 0.22,
      blades: 48,
      bladeLength: 0.43,
      bladeLengthV: 0.14,
      bladeWidth: 0.08,
      bladeThickness: 0.42,
      bladeTaper: 0.52,
      keel: 0.4,
      rolled: 0,
      twist: 8,
      twistV: 10,
      lean: 78,
      leanV: 9,
      droop: 17,
      droopV: 8,
      droopPower: 1.35,
      wave: 1,
      culms: 0,
      head: 'none',
      bladeSegments: 11,
      bladeSides: 8,
      culmSides: 8,
      culmSegments: 10,
      branchletSegments: 2,
      collarRings: 1,
    },
  },
  {
    name: 'Aloe Ferox',
    grass: {
      // Aloe ferox – tall, broad succulent leaves with an upright branched
      // orange-red flower scape. The head is kept sparse so it reads as aloe,
      // not as a generic ornamental grass.
      crownRadius: 0.17,
      crownHeight: 0.045,
      crownSink: 0.004,
      crownProfile: 2.35,
      centreBias: 0.1,
      blades: 46,
      bladeLength: 0.68,
      bladeLengthV: 0.18,
      bladeWidth: 0.064,
      bladeThickness: 0.34,
      bladeTaper: 0.66,
      keel: 0.3,
      rolled: 0,
      twist: 16,
      twistV: 18,
      lean: 62,
      leanV: 14,
      droop: 32,
      droopV: 14,
      droopPower: 1.5,
      wave: 3,
      culms: 1,
      culmHeight: 1.12,
      culmHeightV: 0.1,
      culmRadius: 0.004,
      culmLean: 3,
      culmLeanV: 3,
      culmCurve: 4,
      nodes: 0,
      culmLeafLength: 0.45,
      culmLeafWidth: 0.55,
      culmLeafAngle: 28,
      head: 'panicle',
      headLength: 0.28,
      headWidth: 0.045,
      headDroop: 2,
      headBranches: 18,
      headBranchLength: 0.34,
      headBranchAngle: 18,
      headBranchDroop: 5,
      headBranchSpread: 0.72,
      headBranchRadius: 0.00055,
      headSecondary: 1,
      spikelet: 0.004,
      awn: 0,
      bladeSegments: 11,
      bladeSides: 8,
      culmSides: 8,
      culmSegments: 16,
      branchletSegments: 3,
      collarRings: 1,
    },
  },
  {
    name: 'Yucca Rostrata',
    grass: {
      // Yucca rostrata – blue-beaked yucca: a dense fountain of narrow,
      // powder-blue leaves below a tall cream flower panicle.
      crownRadius: 0.18,
      crownHeight: 0.055,
      crownSink: 0.004,
      crownProfile: 2.55,
      centreBias: -0.04,
      blades: 170,
      bladeLength: 0.82,
      bladeLengthV: 0.16,
      bladeWidth: 0.011,
      bladeThickness: 0.22,
      bladeTaper: 0.78,
      keel: 0.26,
      rolled: 0.12,
      twist: 8,
      twistV: 14,
      lean: 56,
      leanV: 15,
      droop: 38,
      droopV: 18,
      droopPower: 1.6,
      wave: 4,
      culms: 1,
      culmHeight: 2.25,
      culmHeightV: 0.1,
      culmRadius: 0.0065,
      culmLean: 2,
      culmLeanV: 2,
      culmCurve: 3,
      nodes: 0,
      culmLeafLength: 0.45,
      culmLeafWidth: 0.7,
      culmLeafAngle: 24,
      head: 'plume',
      headLength: 0.42,
      headWidth: 0.1,
      headDroop: 3,
      headBranches: 46,
      headBranchLength: 0.27,
      headBranchAngle: 24,
      headBranchDroop: 8,
      headBranchSpread: 0.9,
      headBranchRadius: 0.0007,
      headSecondary: 2,
      spikelet: 0.0025,
      awn: 0,
      bladeSegments: 13,
      bladeSides: 6,
      culmSides: 8,
      culmSegments: 20,
      branchletSegments: 3,
      collarRings: 1,
    },
  },
];

export const GRASS_GROUPS: { label: string; names: string[] }[] = [
  { label: 'Grasses · turf & meadow', names: ['Lawn Turf', 'Meadow Grass', 'Timothy', 'Red Oat Grass'] },
  { label: 'Grasses · tussock', names: ['Blue Fescue', 'Fountain Grass', 'Marram Grass', 'Chinese Silver Grass', 'Pampas Grass'] },
  { label: 'Grasses · cereals & reeds', names: ['Wheat', 'Barley', 'Oat', 'Common Reed', 'Elephant Grass'] },
  { label: 'Desert · succulents', names: ['Century Agave', "Parry's Agave", 'Aloe Vera', 'Desert Spoon', 'Echeveria', 'Haworthia', 'Jade Plant', 'Blue Agave', 'Red Yucca', 'Beargrass', 'Dudleya Rosette', 'Living Stones', 'Snake Plant', 'Queen Victoria Agave', 'Aloe Ferox', 'Yucca Rostrata'] },
];
