import { BuildingConfig } from './generator';

export const BUILDING_PRESETS: Record<string, { name: string; description: string; icon: string; config: BuildingConfig }> = {
  cyberpunk_izakaya: {
    name: "Cyberpunk Izakaya",
    description: "Multi-story Edo-style timber tavern retrofitted with glowing neon, AC compressors, and dense Tokyo telephone cables.",
    icon: "🏮",
    config: {
      seed: 4208,
      archetype: 'izakaya_ramen',
      floors: 3,
      width: 10,
      depth: 9,
      floorHeight: 3.2,
      terraceSetback: 0.15,
      roof: {
        type: 'irimoya',
        overhang: 1.8,
        curvature: 0.7,
        hasTiles: true,
        tileType: 'kawara_honga',
        color: '#1a1f26',
        tileScale: 1.0,
        ridgeOrnament: 'onigawara',
        hasTieredEavesBetweenFloors: true,
      },
      timber: {
        woodType: 'yakisugi',
        bracketStyle: 'dougong_triple',
        bracketDensity: 3,
        hasEngawaBalcony: true,
        balconyRailing: true,
      },
      walls: {
        finish: 'weathered_plank',
        groundFloorStyle: 'shop_noren',
        windowGridDensity: 4,
      },
      electricity: {
        hasPhonePole: true,
        poleDistance: 6.5,
        sagFactor: 0.85,
        wireCount: 5,
        hasTransformers: true,
        hasStreetMirror: true,
        hasACUnits: true,
        acCount: 3,
        hasVendingMachine: true,
        hasUtilityMeters: true,
      },
      lighting: {
        enabled: true,
        hasLanterns: true,
        lanternCount: 5,
        hasNeonSigns: true,
        hasEavesLED: true,
        hasSpotlights: true,
        hasStreetLamp: true,
        lightWarmth: 2400,
        neonColorPrimary: '#f72585',
        neonColorSecondary: '#00f5d4',
        flickerEffect: true,
      },
      furniture: {
        enabled: true,
        hasTatami: true,
        hasChabudaiTable: true,
        hasZafuCushions: true,
        hasShojiScreens: true,
        hasAndonLamp: true,
        hasBonsai: true,
        hasTeaSet: true,
        hasNorenCurtain: true,
      },
      signage: {
        mainSignText: "麺屋・電脳桜",
        mainSignSubtext: "CYBER RAMEN & SAKE BAR",
        mainSignStyle: 'neon_lightbox',
        neonVerticalText: "居酒屋",
        lanternText: "ラーメン",
        norenText: "ゆ",
        hasPosters: true,
        posterType: 'cyber_ad',
        posterTitle: "NEO TOKYO 2099",
      },
      rendering: {
        environment: 'cyberpunk_night',
        bloom: true,
        shadows: true,
        fog: true,
        rain: false,
        autoRotate: false,
      }
    }
  },

  kyoto_machiya: {
    name: "Kyoto Machiya Residence",
    description: "Authentic historic Kyoto merchant townhouse with Senbon-koushi lattice screens, Hinoki cypress, and quiet Zen tatami courtyard.",
    icon: "🏯",
    config: {
      seed: 1042,
      archetype: 'machiya_shop',
      floors: 2,
      width: 8.5,
      depth: 12,
      floorHeight: 3.0,
      terraceSetback: 0.1,
      roof: {
        type: 'irimoya',
        overhang: 1.6,
        curvature: 0.45,
        hasTiles: true,
        tileType: 'kawara_honga',
        color: '#2b2e35',
        tileScale: 1.0,
        ridgeOrnament: 'onigawara',
        hasTieredEavesBetweenFloors: true,
      },
      timber: {
        woodType: 'hinoki',
        bracketStyle: 'tokkyo_simple',
        bracketDensity: 2,
        hasEngawaBalcony: true,
        balconyRailing: true,
      },
      walls: {
        finish: 'clay_earthen',
        groundFloorStyle: 'tatami_shoji',
        windowGridDensity: 5,
      },
      electricity: {
        hasPhonePole: true,
        poleDistance: 6.0,
        sagFactor: 0.6,
        wireCount: 3,
        hasTransformers: true,
        hasStreetMirror: true,
        hasACUnits: true,
        acCount: 1,
        hasVendingMachine: false,
        hasUtilityMeters: true,
      },
      lighting: {
        enabled: true,
        hasLanterns: true,
        lanternCount: 3,
        hasNeonSigns: false,
        hasEavesLED: true,
        hasSpotlights: true,
        hasStreetLamp: true,
        lightWarmth: 2700,
        neonColorPrimary: '#ffb703',
        neonColorSecondary: '#fb8500',
        flickerEffect: false,
      },
      furniture: {
        enabled: true,
        hasTatami: true,
        hasChabudaiTable: true,
        hasZafuCushions: true,
        hasShojiScreens: true,
        hasAndonLamp: true,
        hasBonsai: true,
        hasTeaSet: true,
        hasNorenCurtain: true,
      },
      signage: {
        mainSignText: "古都の茶寮",
        mainSignSubtext: "KYOTO TRADITIONAL ARTISAN",
        mainSignStyle: 'carved_wood',
        neonVerticalText: "茶道",
        lanternText: "御茶",
        norenText: "茶",
        hasPosters: true,
        posterType: 'ukiyo_e',
        posterTitle: "GREAT WAVE OF KANAGAWA",
      },
      rendering: {
        environment: 'dusk_golden',
        bloom: true,
        shadows: true,
        fog: false,
        rain: false,
        autoRotate: false,
      }
    }
  },

  neo_tokyo_office: {
    name: "Neo-Tokyo Studio & Office",
    description: "Hybrid high-tech workplace with Shou Sugi Ban charred timber, seamless glass curtain walls, and industrial rooftop HVAC infrastructure.",
    icon: "🏢",
    config: {
      seed: 8891,
      archetype: 'cyber_office',
      floors: 4,
      width: 12,
      depth: 10,
      floorHeight: 3.4,
      terraceSetback: 0.2,
      roof: {
        type: 'kirizuma',
        overhang: 1.5,
        curvature: 0.2,
        hasTiles: true,
        tileType: 'copper_standing_seam',
        color: '#2a9d8f',
        tileScale: 1.2,
        ridgeOrnament: 'simple_ridge',
        hasTieredEavesBetweenFloors: true,
      },
      timber: {
        woodType: 'cyber_carbon',
        bracketStyle: 'minimal_modern',
        bracketDensity: 2,
        hasEngawaBalcony: true,
        balconyRailing: true,
      },
      walls: {
        finish: 'concrete_modern',
        groundFloorStyle: 'glass_modern',
        windowGridDensity: 3,
      },
      electricity: {
        hasPhonePole: true,
        poleDistance: 7.0,
        sagFactor: 0.7,
        wireCount: 6,
        hasTransformers: true,
        hasStreetMirror: false,
        hasACUnits: true,
        acCount: 4,
        hasVendingMachine: true,
        hasUtilityMeters: true,
      },
      lighting: {
        enabled: true,
        hasLanterns: false,
        lanternCount: 0,
        hasNeonSigns: true,
        hasEavesLED: true,
        hasSpotlights: true,
        hasStreetLamp: true,
        lightWarmth: 4000,
        neonColorPrimary: '#00b4d8',
        neonColorSecondary: '#7209b7',
        flickerEffect: false,
      },
      furniture: {
        enabled: true,
        hasTatami: true,
        hasChabudaiTable: true,
        hasZafuCushions: false,
        hasShojiScreens: true,
        hasAndonLamp: true,
        hasBonsai: true,
        hasTeaSet: true,
        hasNorenCurtain: false,
      },
      signage: {
        mainSignText: "創世研究所",
        mainSignSubtext: "SYNAPSE DYNAMICS TOKYO",
        mainSignStyle: 'cyber_hologram',
        neonVerticalText: "研究所",
        lanternText: "電脳",
        norenText: "創",
        hasPosters: true,
        posterType: 'cyber_ad',
        posterTitle: "QUANTUM NEURAL INTERFACE",
      },
      rendering: {
        environment: 'cyberpunk_night',
        bloom: true,
        shadows: true,
        fog: true,
        rain: false,
        autoRotate: false,
      }
    }
  },

  shrine_residence: {
    name: "Sacred Shrine Residence",
    description: "Vibrant Vermilion-lacquered timber sanctuary with sweeping Chinese Dian eaves, sacred bronze dragon finials, and ritual paper lanterns.",
    icon: "⛩️",
    config: {
      seed: 7721,
      archetype: 'shrine_residence',
      floors: 2,
      width: 11,
      depth: 10,
      floorHeight: 3.6,
      terraceSetback: 0.1,
      roof: {
        type: 'chinese_dian',
        overhang: 2.2,
        curvature: 1.1,
        hasTiles: true,
        tileType: 'glazed_imperial',
        color: '#c1121f',
        tileScale: 1.0,
        ridgeOrnament: 'shibi_dragon',
        hasTieredEavesBetweenFloors: true,
      },
      timber: {
        woodType: 'vermilion_lacquer',
        bracketStyle: 'dougong_triple',
        bracketDensity: 4,
        hasEngawaBalcony: true,
        balconyRailing: true,
      },
      walls: {
        finish: 'shikkui_white',
        groundFloorStyle: 'tatami_shoji',
        windowGridDensity: 4,
      },
      electricity: {
        hasPhonePole: true,
        poleDistance: 6.5,
        sagFactor: 0.6,
        wireCount: 3,
        hasTransformers: true,
        hasStreetMirror: true,
        hasACUnits: false,
        acCount: 0,
        hasVendingMachine: false,
        hasUtilityMeters: true,
      },
      lighting: {
        enabled: true,
        hasLanterns: true,
        lanternCount: 6,
        hasNeonSigns: false,
        hasEavesLED: true,
        hasSpotlights: true,
        hasStreetLamp: true,
        lightWarmth: 2200,
        neonColorPrimary: '#ff0054',
        neonColorSecondary: '#ffbd00',
        flickerEffect: false,
      },
      furniture: {
        enabled: true,
        hasTatami: true,
        hasChabudaiTable: true,
        hasZafuCushions: true,
        hasShojiScreens: true,
        hasAndonLamp: true,
        hasBonsai: true,
        hasTeaSet: true,
        hasNorenCurtain: true,
      },
      signage: {
        mainSignText: "稲荷大明神",
        mainSignSubtext: "SACRED INARI SHRINE SANCTUARY",
        mainSignStyle: 'brass_plate',
        neonVerticalText: "神道",
        lanternText: "奉納",
        norenText: "神",
        hasPosters: true,
        posterType: 'ukiyo_e',
        posterTitle: "SACRED MOUNT FUJI",
      },
      rendering: {
        environment: 'dusk_golden',
        bloom: true,
        shadows: true,
        fog: false,
        rain: false,
        autoRotate: false,
      }
    }
  },

  pagoda_tower: {
    name: "Five-Tier Pagoda Tower",
    description: "Multi-tiered stepped architectural monument with authentic Dou-gong brackets, projecting eaves, and an ornate Sorin bronze spire.",
    icon: "🗼",
    config: {
      seed: 5543,
      archetype: 'pagoda_tower',
      floors: 5,
      width: 9,
      depth: 9,
      floorHeight: 3.2,
      terraceSetback: 0.18,
      roof: {
        type: 'pagoda_stepped',
        overhang: 2.0,
        curvature: 0.8,
        hasTiles: true,
        tileType: 'kawara_honga',
        color: '#1d2a44',
        tileScale: 1.0,
        ridgeOrnament: 'shibi_dragon',
        hasTieredEavesBetweenFloors: true,
      },
      timber: {
        woodType: 'keyaki',
        bracketStyle: 'dougong_triple',
        bracketDensity: 3,
        hasEngawaBalcony: true,
        balconyRailing: true,
      },
      walls: {
        finish: 'shikkui_white',
        groundFloorStyle: 'tatami_shoji',
        windowGridDensity: 3,
      },
      electricity: {
        hasPhonePole: true,
        poleDistance: 7.5,
        sagFactor: 0.8,
        wireCount: 4,
        hasTransformers: true,
        hasStreetMirror: false,
        hasACUnits: false,
        acCount: 0,
        hasVendingMachine: true,
        hasUtilityMeters: true,
      },
      lighting: {
        enabled: true,
        hasLanterns: true,
        lanternCount: 8,
        hasNeonSigns: true,
        hasEavesLED: true,
        hasSpotlights: true,
        hasStreetLamp: true,
        lightWarmth: 2500,
        neonColorPrimary: '#00f5d4',
        neonColorSecondary: '#fee440',
        flickerEffect: false,
      },
      furniture: {
        enabled: true,
        hasTatami: true,
        hasChabudaiTable: true,
        hasZafuCushions: true,
        hasShojiScreens: true,
        hasAndonLamp: true,
        hasBonsai: true,
        hasTeaSet: true,
        hasNorenCurtain: false,
      },
      signage: {
        mainSignText: "五重の塔",
        mainSignSubtext: "TEMPLE OF TRANQUILITY",
        mainSignStyle: 'carved_wood',
        neonVerticalText: "寺院",
        lanternText: "平和",
        norenText: "道",
        hasPosters: false,
        posterType: 'ukiyo_e',
        posterTitle: "ZEN LOTUS",
      },
      rendering: {
        environment: 'kyoto_day',
        bloom: true,
        shadows: true,
        fog: false,
        rain: false,
        autoRotate: false,
      }
    }
  },

  zen_tea_house: {
    name: "Zen Tea House Pavilion",
    description: "Rustic single-story tea sanctuary with split bamboo roof tiles, weathered timber, wrap-around engawa deck, and peaceful tea ceremony setup.",
    icon: "🍵",
    config: {
      seed: 3312,
      archetype: 'tea_house',
      floors: 1,
      width: 8,
      depth: 7,
      floorHeight: 3.0,
      terraceSetback: 0.0,
      roof: {
        type: 'yosemune',
        overhang: 1.8,
        curvature: 0.35,
        hasTiles: true,
        tileType: 'bamboo_split',
        color: '#588157',
        tileScale: 1.0,
        ridgeOrnament: 'simple_ridge',
        hasTieredEavesBetweenFloors: false,
      },
      timber: {
        woodType: 'weathered_timber',
        bracketStyle: 'tokkyo_simple',
        bracketDensity: 2,
        hasEngawaBalcony: true,
        balconyRailing: false,
      },
      walls: {
        finish: 'clay_earthen',
        groundFloorStyle: 'tatami_shoji',
        windowGridDensity: 4,
      },
      electricity: {
        hasPhonePole: false,
        poleDistance: 6.0,
        sagFactor: 0.5,
        wireCount: 2,
        hasTransformers: false,
        hasStreetMirror: false,
        hasACUnits: false,
        acCount: 0,
        hasVendingMachine: false,
        hasUtilityMeters: false,
      },
      lighting: {
        enabled: true,
        hasLanterns: true,
        lanternCount: 2,
        hasNeonSigns: false,
        hasEavesLED: true,
        hasSpotlights: true,
        hasStreetLamp: false,
        lightWarmth: 2400,
        neonColorPrimary: '#ffb703',
        neonColorSecondary: '#fb8500',
        flickerEffect: false,
      },
      furniture: {
        enabled: true,
        hasTatami: true,
        hasChabudaiTable: true,
        hasZafuCushions: true,
        hasShojiScreens: true,
        hasAndonLamp: true,
        hasBonsai: true,
        hasTeaSet: true,
        hasNorenCurtain: true,
      },
      signage: {
        mainSignText: "無心庵",
        mainSignSubtext: "MUSHIN ZEN TEA ROOM",
        mainSignStyle: 'carved_wood',
        neonVerticalText: "茶道",
        lanternText: "侘寂",
        norenText: "茶",
        hasPosters: false,
        posterType: 'ukiyo_e',
        posterTitle: "ZEN ENKI",
      },
      rendering: {
        environment: 'dusk_golden',
        bloom: true,
        shadows: true,
        fog: false,
        rain: false,
        autoRotate: false,
      }
    }
  }
};
