#!/usr/bin/env python3
# ======================================================================================================================
# GenerateVehicleHeaders.py -- emit the Project-Drive mesh headers from controlvehicle_scene.json.
#
# Replaces MeshToHeader.py.  The difference that matters: every triangle now carries the material family the artist
# assigned in Blender, so DriveSceneAuthor no longer has to guess the paint/glass/plastic split from face positions.
#
# Emits:
#   ControlVehicleMesh.inl       body group (ControlVehicle + Interiror + PROTO-X.001/.002) in the MODEL frame,
#                                with a per-triangle material family stream
#   ControlVehicleWheelMesh.inl  one rim and one tyre in HUB-LOCAL coordinates, for instancing at the four axle
#                                sockets.  These are the authored RimFL/RubberFL meshes -- the wheels the .blend
#                                actually ships, complete with mags -- not procedural bands.
#
# The model frame is load-bearing and unchanged: ground is model Z -0.41715 (axle 0.0914 - tyre radius 0.50855).
# ======================================================================================================================
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
DST = os.path.abspath(os.path.join(HERE, '..', '..', 'Overlay', 'Projects', 'Project-Drive', 'Source'))
S = json.load(open(os.path.join(HERE, 'controlvehicle_scene.json')))
OBJ = {o['name']: o for o in S['objects']}

# Canonical material families, index-aligned with DriveCourse.h CourseMaterial.  The .blend material name is the
# authority; every one of the eleven authored materials gets a home rather than being folded into a guess.
FAMILY = [
    ('MetalicCoat',        'MatBodyPaint',      6),
    ('Glass',              'MatVehicleGlass',   7),
    ('Plastic',            'MatVehiclePlastic', 8),
    ('Rubber',             'MatTyre',           9),
    ('StandardRubber.002', 'MatTyre',           9),
    ('Material.024',       'MatHub',           10),
    ('Plastic2',           'MatVehicleTrim',   12),
    ('FrontLight',         'MatHeadLight',     13),
    ('RearLight',          'MatTailLight',     14),
    ('Material.016',       'MatVehicleDark',   15),
    ('Dots Stroke',        'MatVehicleDark',   15),
]
SLOT = {name: idx for name, _, idx in FAMILY}
UNASSIGNED = 16                       # PROTO-X.002 carries totcol = 0 in the .blend; Blender's own default grey

BODY = ['ControlVehicle', 'Interiror', 'PROTO-X.001', 'PROTO-X.002']
AXLE_FL = (1.7274, 1.0475, 0.0914)    # Socket_AxleMount_FL, the hub-local origin


def gather(names, origin=None):
    """Merge the named objects into one vertex/triangle/material stream, optionally rebased about `origin`."""
    verts, tris, mats = [], [], []
    for n in names:
        o = OBJ[n]
        base = len(verts)
        for v in o['verts']:
            verts.append(v if origin is None else [v[i] - origin[i] for i in range(3)])
        for t, mi in zip(o['tris'], o['tri_material']):
            tris.append([t[0] + base, t[1] + base, t[2] + base])
            slots = o['slots']
            mats.append(SLOT.get(slots[mi], UNASSIGNED) if mi < len(slots) else UNASSIGNED)
    return verts, tris, mats


def fmt_floats(vals, per_line=12):
    out, line = [], []
    for i, v in enumerate(vals):
        line.append('%.5ff' % v)
        if len(line) == per_line:
            out.append('  ' + ','.join(line) + ','); line = []
    if line:
        out.append('  ' + ','.join(line) + ',')
    return '\n'.join(out).rstrip(',')


def fmt_ints(vals, per_line=18, suffix='u'):
    out, line = [], []
    for v in vals:
        line.append('%d%s' % (v, suffix))
        if len(line) == per_line:
            out.append('  ' + ','.join(line) + ','); line = []
    if line:
        out.append('  ' + ','.join(line) + ',')
    return '\n'.join(out).rstrip(',')


def emit(path, ns, verts, tris, mats, note):
    xs = [v[0] for v in verts]; ys = [v[1] for v in verts]; zs = [v[2] for v in verts]
    flat = [c for v in verts for c in v]
    idx = [i for t in tris for i in t]
    used = sorted(set(mats))
    with open(path, 'w') as f:
        f.write('// %s -- GENERATED by CarModelling/ControlVehicle/GenerateVehicleHeaders.py. Do not edit by hand.\n'
                % os.path.basename(path))
        f.write('// Source: controlvehicle_scene.json  (%s: %d verts / %d tris)\n' % (ns, len(verts), len(tris)))
        f.write('// %s\n' % note)
        f.write('// Bounds  X[%.4f,%.4f]  Y[%.4f,%.4f]  Z[%.4f,%.4f]  (metres, +X fwd / +Y left / +Z up)\n'
                % (min(xs), max(xs), min(ys), max(ys), min(zs), max(zs)))
        f.write('// kTriangleMaterial holds the family the artist assigned in Blender, index-aligned with\n'
                '// DriveCourse.h CourseMaterial.  Families present here: %s\n' % ', '.join(str(u) for u in used))
        f.write('#pragma once\n#include <cstdint>\nnamespace Frontier { namespace Drive { namespace %s {\n' % ns)
        f.write('inline constexpr uint32_t kVertexCount   = %du;\n' % len(verts))
        f.write('inline constexpr uint32_t kTriangleCount = %du;\n' % len(tris))
        f.write('inline constexpr float kBoundsMin[3] = { %.6ff, %.6ff, %.6ff };\n' % (min(xs), min(ys), min(zs)))
        f.write('inline constexpr float kBoundsMax[3] = { %.6ff, %.6ff, %.6ff };\n' % (max(xs), max(ys), max(zs)))
        f.write('inline constexpr float kPositions[] = {\n%s\n};\n' % fmt_floats(flat))
        f.write('inline constexpr uint32_t kTriangles[] = {\n%s\n};\n' % fmt_ints(idx))
        f.write('inline constexpr uint32_t kTriangleMaterial[] = {\n%s\n};\n' % fmt_ints(mats))
        f.write('} } } // namespace Frontier::Drive::%s\n' % ns)
    return used


def main():
    # ---- body ------------------------------------------------------------------------------------------------
    v, t, m = gather(BODY)
    used = emit(os.path.join(DST, 'ControlVehicleMesh.inl'), 'ControlVehicleMesh', v, t, m,
                'Body group in the MODEL frame; ground is model Z -0.41715.')
    hist = {u: m.count(u) for u in used}
    print('ControlVehicleMesh.inl   %d verts / %d tris   families %s' % (len(v), len(t), hist))

    # ---- wheel (rim + tyre, hub-local) -----------------------------------------------------------------------
    vr, tr, mr = gather(['RimFL'], AXLE_FL)
    ur = emit(os.path.join(DST, 'ControlVehicleRimMesh.inl'), 'ControlVehicleRimMesh', vr, tr, mr,
              'Authored RimFL in HUB-LOCAL coordinates about Socket_AxleMount_FL (1.7274, 1.0475, 0.0914).')
    print('ControlVehicleRimMesh.inl  %d verts / %d tris   families %s' % (len(vr), len(tr), {u: mr.count(u) for u in ur}))

    vt, tt, mt = gather(['RubberFL'], AXLE_FL)
    ut = emit(os.path.join(DST, 'ControlVehicleTyreMesh.inl'), 'ControlVehicleTyreMesh', vt, tt, mt,
              'Authored RubberFL in HUB-LOCAL coordinates about Socket_AxleMount_FL (1.7274, 1.0475, 0.0914).')
    zs = [p[2] for p in vt]; ys = [p[1] for p in vt]
    print('ControlVehicleTyreMesh.inl %d verts / %d tris   families %s' % (len(vt), len(tt), {u: mt.count(u) for u in ut}))
    print('   tyre hub-local radius %.5f  half-width %.5f' % (max(zs), (max(ys) - min(ys)) * 0.5))


if __name__ == '__main__':
    main()
