/** Frontier — export helpers: OBJ (for Blender and any DCC) + JSON report. */
export function toOBJ(parts, { scale = 1, groups = true } = {}) {
  const out = [];
  out.push('# Frontier — procedural East Asian roof');
  out.push('# generated by src/core/build-roof.js (see docs/ROOF_RESEARCH.md)');
  let offset = 1;
  for (const p of parts) {
    if (!p.positions.length) continue;
    if (groups) out.push(`g ${p.layer}.${p.id}`);
    out.push(`usemtl ${p.material}`);
    const P = p.positions;
    for (let i = 0; i < P.length; i += 3) {
      out.push(`v ${(P[i] * scale).toFixed(6)} ${(P[i + 1] * scale).toFixed(6)} ${(P[i + 2] * scale).toFixed(6)}`);
    }
    for (let i = 0; i < P.length / 9; i++) {
      const a = offset + i * 3;
      out.push(`f ${a} ${a + 1} ${a + 2}`);
    }
    offset += P.length / 3;
  }
  return out.join('\n');
}

/**
 * Streaming OBJ writer — a 2.7 M-triangle roof is several hundred MB of text, far more
 * than `toOBJ`'s array-of-lines can hold, so the CLI writes it progressively.
 */
export function writeOBJStream(parts, stream, { scale = 1, groups = true } = {}) {
  stream.write('# Frontier — procedural East Asian roof\n# generated by src/core/build-roof.js (see docs/ROOF_RESEARCH.md)\n');
  let offset = 1;
  const CHUNK = 20000;
  for (const p of parts) {
    if (!p.positions.length) continue;
    if (groups) stream.write(`g ${p.layer}.${p.id}\n`);
    stream.write(`usemtl ${p.material}\n`);
    const P = p.positions;
    let buf = [];
    for (let i = 0; i < P.length; i += 3) {
      buf.push(`v ${(P[i] * scale).toFixed(6)} ${(P[i + 1] * scale).toFixed(6)} ${(P[i + 2] * scale).toFixed(6)}`);
      if (buf.length >= CHUNK) { stream.write(buf.join('\n') + '\n'); buf = []; }
    }
    const nFaces = P.length / 9;
    for (let i = 0; i < nFaces; i++) {
      const a = offset + i * 3;
      buf.push(`f ${a} ${a + 1} ${a + 2}`);
      if (buf.length >= CHUNK) { stream.write(buf.join('\n') + '\n'); buf = []; }
    }
    if (buf.length) stream.write(buf.join('\n') + '\n');
    offset += P.length / 3;
  }
}

export function materialList(parts) {
  return [...new Set(parts.map((p) => p.material))];
}

export function toJSONReport(roof, validation) {
  const r = roof.report;
  return {
    generated: new Date().toISOString(),
    form: roof.spec.form,
    spec: roof.spec,
    tile: r.tile,
    geometry: {
      ridgeLengthM: r.ridgeLength, hipRunM: r.hipRun, pitchDeg: r.pitchDeg,
      roofAreaM2: r.totalRoofArea, laidTileAreaM2: r.laidTileArea,
      tileMassKg: r.massEstimateKg, cornerSweep: r.sweep,
      faces: r.faces, counts: r.counts,
    },
    validation: validation ? {
      pass: validation.pass,
      checks: validation.checks.map((c) => ({ id: c.id, ok: c.ok, value: c.value, tolerance: c.tolerance })),
      summary: validation.summary,
    } : null,
    layers: roof.parts.map((p) => ({ id: p.id, layer: p.layer, material: p.material, triangles: p.triCount })),
  };
}
